### ISSUE TITLE
root subvol circular reference

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1005]
In my rummage through the filesystem I found that /root is the same as /mnt2/root/root and can create a circular reference when doing a $find / -name blah . I'm guessing this is a Btrfs layout but cant find an explanation. Maybe include that in the docs?

http://forum.rockstor.com/t/docker-and-btrfs-quite-a-learning-curve/645

**Comment by sfranzen** [comment]
Forum user Learning2NAS recently found himself in an unfortunate [permission hell](https://forum.rockstor.com/t/changing-permissions-may-have-broken-my-system/2011):

> After having trouble with one of my shares, I decided to review all of the permissions on all of my shares. I noticed that "Other" was set to allow Read and Execute. I didn't know what (or who) "Other" might be, so I systematically went down the line and disabled all permissions for "Other" on each of my shares. When I disabled "Other" on my root share, the box crashed and has become totally inaccessible. The root share was already owned by root and in the root group, so why does "Other" need access? Is there a way to fix this without reinstalling? Any help is much appreciated.

I'm unsure whether allowing such a dangerous command to be executed from the web interface without a warning is a good idea, especially since a user may not be aware that this is in fact the root subvolume. On the other hand, having this share mounted and listed with the other shares does allow the user the same control over compression and snapshots, which is nice.

Perhaps the best solution is to either `chattr +i /mnt2/root` or just "softly" disable its permissions to be changed from the UI.

**Comment by phillxnet** [comment]
We now have a radically different btrfs layout re openSUSE, and any cli intervention is advance by nature. Closing by way of issue house-keeping.
