### ISSUE TITLE
Cannot Turn Off Active Directory Service

### ISSUE THREAD

**Issue by djeraseit** [rockstor/rockstor-core#1041]
Error!
 

Missing configuration. Please configure the service and try again. Exception: expected string or buffer

**Comment by phillxnet** [comment]
@djeraseit This was an issue we had with non updated Rockstor, among a few others. Could you please try updating on the testing channel for now as this and many other issues have now been addressed. Please see closed issue #1029 and the following forum posts:-
http://forum.rockstor.com/t/dev-log-for-upcoming-3-8-10/656/20
and
http://forum.rockstor.com/t/why-are-sftp-and-active-directory-enabled-now/658

The fixes in testing will be incorporated into stable in the near future.

If you could apply the testing channel updates and confirm that this issue is fixed for you then that would be a welcome confirmation, and if so then please feel free to comment and close the issue if you are happy to do that.

@schakrava I think this issue is a duplicate of closed issue #1029

**Comment by djeraseit** [comment]
Thank you for your quick response. I am very excited about this project and should probably search issues first before posting.
