### ISSUE TITLE
Create Place for User-Rock-Ons and integrate into GUI (extend rockon-registry)

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1142]
(very) few user-provided Rock-Ons exist.
Unfortunately, they are hidden somewhere in the Forum.

It would be good, if users could easily add them to a separated section of the rockon-registry (e.g. testing/unstable/whatever)

Then users should be able to select and install these Rock-Ons from the Web-Interface of RockStor.

In addition, a rating system would be good. After some positive ratings, a RockOn could be moved into the main rockon-registry.

**Comment by Hooverdan96** [comment]
@FroggyFlox is this still relevant? I don't know whether this was written before the Rockon transaction/list was established, but I would think that for this specific description above, the issue is actually resolved and should be closed.
Obviously that doesn't end the running debate on what's the best way for docker type integrations is :).
