### ISSUE TITLE
When Reloading the list of available Rock-Ons a Conflict arises if a custom Rock-On is installed already

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1179]
Hello,

I am using two custom rockons. Squeezebox and Crashplan.
Reloading the list of available RockOns triggers this error:

Error!

Errors occurred while processing updates for following Rock-ons. CrashPlan: Cannot add/remove volume definitions of the container(Crashplan) as it belongs to an installed Rock-on(CrashPlan). Uninstall it first and try again.

[error (3).tgz.zip](https://github.com/rockstor/rockstor-core/files/139638/error.3.tgz.zip)
Attached you find the logs (which I had to rename to .zip to cheat on the limitation of github allowing no tgz files.

Greetings,
Hendrik

**Comment by bskrtich** [comment]
I am running in to this same issue. I think it has to do with adding extra shares to any of your Rockons. In the code it compares the number of shares that you have configured to the number of shares in the config and if the number is different it wants to wipe out all the defined shares and re-setup up but because you have the rockon installed it stops the system from doing that and just throws this error. I am working on a fix for this issue.

**Comment by henfri** [comment]
Thanks!
Am 09.06.2016 23:14 schrieb Brandon Skrtich <notifications@github.com>:I am running in to this same issue. I think it has to do with adding extra shares to any of your Rockons. In the code it compares the number of shares that you have configured to the number of shares in the config and if the number is different it wants to wipe out all the defined shares and re-setup up but because you have the rockon installed it stops the system from doing that and just throws this error. I am working on a fix for this issue.

**Comment by schakrava** [comment]
I don't think it's a good idea to try to add a custom Rock-on with the same name while one is already installed. What purpose does it serve? Why not use a different name for the custom Rock-on? or why not un-install and then add the custom one?

**Comment by FroggyFlox** [comment]
Closing this issue as it has been waiting for feedback for a long time.
