### ISSUE TITLE
Services sort by status is not functional.

### ISSUE THREAD

**Issue by tastyratz** [rockstor/rockstor-core#1201]
Minor bug I noticed. I can sort by name but sort by status button exists and does not change anything.

**Comment by MFlyer** [comment]
Status col doesn't get sorted because of missing text
Service name col has always a pure text inside td (service name), while status col has only checkbox & others, but not a simple text to perform sort on 
Done a test adding like a simple text inside the status td ({{getStatus this.status}} that returns empty or checked) and sorting is working

Add: on ajax call to check status changes cols sort again by service name

@schakrava

**Comment by MFlyer** [comment]
@schakrava to be closed

**Comment by schakrava** [comment]
Fixed by #1258. Thanks @MFlyer
