### ISSUE TITLE
btrfs.py

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1223]
Hi Suman, as i told via private msg on Rockstor forum you'll get a rescan for every files grater than 4K, so I think it would be easier just to add "--rescan" to qgroup assign instead of performing more checks as done over 3.8.12-04 upgrade

Latest thing to check is if it btrfs-progs change behavior on version 4.5

**Comment by schakrava** [comment]
Good point, but I am ahead of you here. --rescan is good but it's not idempotent. So, suppose you create a new snapshot and there's a scan already running, it throws an error. Which means, we have to check for it anyway. That's why I've implemented a cleaner logic in 3.8.12-04.

Btw, Any more snapshot creation errors in 3.8.12-04?

**Comment by MFlyer** [comment]
None, just tons of debug about rescan, but not any error :+1:
