### ISSUE TITLE
graceful shutdown with cron job 

### ISSUE THREAD

**Issue by gkellar** [rockstor/rockstor-core#1306]
I am trying to schedule rockstor to shutdown at 4:00 a.m. every morning. I currently use a cronjob: "shutdown -h now
The machine shuts down on schedule but randomly does not shutdown gracefully. In particular, randomly, after shutting down, it will not restart properly. A forced restart at that point will correct the situation. How can I "gracefully" shut down rockstor at a set time?
Thanks in advance

**Comment by MFlyer** [comment]
Hi @gkellar, actually Rockstor doesn't have a "cron manager" for tasks different from web ui tasks (snapshots, scrub and replica) - We'll add a cron manager asap because it's a useful feature requested by other users too

Actually Rockstor web ui shutdown = shutdown -h now, so that should be ok

Flyer

**Comment by phillxnet** [comment]
@gkellar @MFlyer I have seen Rockstor's shutdown, which as @MFlyer points out is simply a "shutdown -h now", hang at a very late stage but only when installed on USB, when the same hw was used but with a non USB boot device this occasional failure to fully shutdown was no longer observed.
I put this down to being related to the current upstream kernel issues re USB system drives.
@roweryan looked into the kernel USB issue and reported on this in comments within the following issue:- https://github.com/rockstor/rockstor-core/issues/1069
see post dated 31st Jan. Apparently this is now sorted in kernel versions >= 4.5.0.

My own experience of non clean shutdowns ie no actual power off due to kernel panic or unmount issues were with Rockstor installed on SanDisk Extreme USB 3.0 32GB.

Linking to our open issue for "Custom Cron Jobs via WebGUI":
https://github.com/rockstor/rockstor-core/issues/1036
to show the additional interest.

**Comment by MFlyer** [comment]
To @schakrava : this can be closed, missing "Fixes" statement over recent PR

Mirko

**Comment by schakrava** [comment]
Nice work on this @MFlyer . Thank you!
