### ISSUE TITLE
sort by size in snapshots table view not working 

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1368]

**Comment by gkadillak** [comment]
@priyaganti could you provide more clarification? What do you mean by 'not working'?

**Comment by phillxnet** [comment]
I think the issue here is the nature of the sort.
It would appear that we are currently sorting by a suspected sting/lexicographical not a unit aware numeric:
ie currently from largest to smallest:

96.00 KB
80.00 KB
64.00 KB
6.62 MB
6.61 MB
6.59 MB
59.09 MB
5.23 MB
200.00 KB
16.00 KB
ie 9, 8, 6, 5, 2, 1 as first digit.

Tested for both Total and Exclusive Size sort.
