### ISSUE TITLE
[Minor issue] Share creation - better UI & code refactoring

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1512]
Ref to
https://forum.rockstor.com/t/share-size-must-be-an-integer/1912/
https://forum.rockstor.com/t/enhancement-enlage-field-size-on-shares-page/2297/

Had same issue one/two months ago and had some check on it: our issue not on backend, but on frontend js d3 slider.

M.

**Comment by tomtom13** [comment]
@MFlyer could you please remove limit for size on slide OR provide a tick box saying "enable over provision" that will let users exceed current available size ?

**Comment by MFlyer** [comment]
@tomtom13 why ? O_o

**Comment by tomtom13** [comment]
I think I've explained this in forum,

I've had a situation where I've create a pool with single share and filled the FS up to 50%, then went on to create a second share and could not span it across 100% of pool space. I want two shares dynamically fight for space and not use quotas. 

On forum I think @schakrava does agree that it should be to users choice whenever to / not to use quotas and how to configure those.

Let's say user got a 1 share in 1 pool. share is filled to 90%, they want to migrate ALL data to share that they are about to create ... I know that quotas don't work right now, but when they will start working we will end up with a massive can of worms.

**Comment by tomtom13** [comment]
still, @MFlyer you need to understand that quota means that you want something not to be bigger than X, not that it's not bigger than free space.

I've used quotas in my life and you can freely say that you want for example user difrectories not to be bigger than 1GB for 500 users on 300GB disk. Yes this is cheating, because you over provisioned but usually people will not get near a allowed 1GB

Also in current setup if you setup a single pool with 1 share and allocate a 100% to it, who says you can allocate any more space to any new share ?!?!?!?! letting in user create a share with what ever free space is on the disk is alreade creating a over provisioned setup - because first share has 100% and second has a bit more.

**Comment by MFlyer** [comment]
You're right Tom, I agree on that, but actually "downgrading" that slider doesn't make sense: it will be anyway required over quotas (updrage: have slider on quota enabled, no slider if no quota!)

M.

**Comment by tomtom13** [comment]
so how with this slider and quotas enabled I can setup a 1TB pool with 3 shares each allowed 500GB after filling first share to 600GB and than creating reminding shares ? 

I know what you are trying to achieve, but because ewe don't keep track of allocated size for other shares this slider is NOT functioning as intended.

**Comment by MFlyer** [comment]
Actually you can have that slider with 1KB on each share of your 1TB pool and those 3 shares will fight for space (yes, there's not real check over it)

**Comment by tomtom13** [comment]
Ok, but when quotas will get enabled and share size will be enforced - then what ... ??

How about we resolve this problem before we will have an avalanche of people "my system is not responding" or "my system is dead - it's your fault you tw****"

**Comment by MFlyer** [comment]
> How about we resolve this problem before we will have an avalanche of people "my system is not responding" or "my system is dead - it's your fault you tw****"

@schakrava - @phillxnet - @sfranzen probably intereste in this too
That's exactly what we all have to care to: when enabling quotas we'll have to care about existing shares/Rockstor system and let it be a soft update (no auto quota on update, user will have a warning like "hey man, you're enabling quota on this share, pls remember on this pool you've other shares too)
M.

**Comment by tomtom13** [comment]
Ok, that's great ... still what about a use case: 
"
so how with this slider and quotas enabled I can setup a 1TB pool with 3 shares each allowed 500GB after filling first share to 600GB and than creating reminding shares ? 
"
quotas are to disallow excising certain size. not making sure that everything fits within the pool. Still user should be able to set quota to what ever tickles their fancy. Why quota tool does not return to you saying "hay man you FS is only 4TB and you set quota to 5TB" you can set perfectly walid quota to over the FS size and it's OK, because everybody knows that you can add more storage in few minutes ... of use thin provisioning.

**Comment by MFlyer** [comment]
Hi @tomtom13 I understand you and probably when adding quota feature we'll need a briefing to decide all together how to implement it & how to handle existing Rockstor instances to avoid users accidentally loose data etc etc!
M.

**Comment by tomtom13** [comment]
@MFlyer 
https://forum.rockstor.com/t/leaving-rockstor/2367
and from my experience, one in thousand users that turn down your product will sound their opinion, so even thought it's rough ... we should look at making stuff simpler.

can we have a checkbox for global disable of quotas ? I'm now having similar issues as well ... my 8 x 2tb raid10 can only spit out 180MB throughput on sequential reads (dd -> /dev/zero)

ps I think that bes solution would be to have per pool tick box "enable quota share size limitations"

**Comment by MFlyer** [comment]
Hi @tomtom13 ,
having quota disabled isn't a "1 line code commit", both @phillxnet & @schakrava can confirm it ("some" tests required too)
Easy way: rollback to btrfs-progs 4.6... ?!?

Talking about that post: I don't wanna talk about that post, I don't want start being unpolite.

M.

**Comment by phillxnet** [comment]
@tomtom13 Maybe you could open a new GitHub issue with this as a feature request as this issue is now closed. Or better still start a forum thread to have a little open discussion on how best this might be implemented first, or in fact if it is even desired: especially given typical network speeds and the onward march of quotas upstream.

**Comment by tomtom13** [comment]
@MFlyer @phillxnet   I know that it's not a one liner ... I want to convince people that we should aim at ease with possibility of extra config. Quotas are in my mind what makes 90% users confused.com .... just ask a normal user "what is quota" to see the point here ... and on top of that we get penalty in performance.

I know @MFlyer that this post can make somebody left upset ... maybe he's even 99% wrong ... but then there is a 1% where he's right ...
