### ISSUE TITLE
Regression in 3.8.15 - not able to set samba workgroup - spits out an error

### ISSUE THREAD

**Issue by tomtom13** [rockstor/rockstor-core#1515]
Just FYI:

`            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/smart_manager/views/samba_service.py", line 83, in post
    update_global_config(global_config, adconfig)
  File "/opt/rockstor/src/rockstor/system/samba.py", line 134, in update_global_config
    tfo.write('    %s = %s\n' % (k, ad_config[k]))
KeyError: 'workgroup'`

I've tried a lot different names and everything returns error - even the example from info balon "mygroup" ( or "MYGROUP" :D )

**Comment by MFlyer** [comment]
@tomtom13 : check my comment on PR :)

M.

**Comment by phillxnet** [comment]
@tomtom13 Thanks for opening this and updating accordingly re dup status etc and your contributions on issue #1495 and your prompt but unfortunately redundant pr #1516.

Given the referenced duplicate issue of #1495 is now fixed by pr #1496 are you happy to close this issue as:
Fixed by #1496 ?
Thanks.

**Comment by tomtom13** [comment]
Damn, I thought I done that :/ 
Fixed by #1496
