### ISSUE TITLE
Services config edit broken

### ISSUE THREAD

**Issue by tastyratz** [rockstor/rockstor-core#1528]
I updated to current up to version 3.8.15-6 today.

I decided to go into services to edit config but when clicking the wrench next to any services the page only drops a line with extra whitespace at the top. The URL bar updates but does nothing.
If I manually open the URL (i.e. https://192.168.1.21/home#services/active-directory/edit) in another tab I get the same result.
Refreshing the page, restarting Rockstor, trying in chrome OR firefox, and dumping cache nets the same result.
If I try to click and enable Rock-on service for example I still get the overlay warning me that I have not yet configured it so I know pops are functional on that page.

I do not know when the last time this was accessed successfully.

**Comment by phillxnet** [comment]
@tastyratz Thanks for reporting.
@MFlyer does this relate to today's changes in 3.8.15-6 ?

**Comment by MFlyer** [comment]
Hi @phillxnet nothing on 3.8.15-6 related to services / services config related (checked edited files too on https://github.com/rockstor/rockstor-core/pull/1510/files and none of services configuration).

Possible issue: new socket.io lib downloaded & something cached, but nothing a good reboot + page refresh can solve

@tastyratz can you please provide some console logs from Chrome and/or firefox??

Thanks

**Comment by MFlyer** [comment]
Update: @phillxnet & @tastyratz  that's my fault, sorry!, and I think while checking @schakrava didn't catch it too because probably had an env in a state equal to mine (was checking same things)

router.js file has #1501 modal settings, had modal views code before python-socketio migration, so my suspicion is that I had an open router.js from modal views branch when i added that 1-2 lines required by python-socketio : guys really sorry about that :/

How to easy solve this @schakrava : merge modal view PR that I'll had a PR on the glitch problem

Once again sorry
M.

**Comment by tastyratz** [comment]
I tried turning on developer options on that page and watching the console but didn't see anything. 
Let me know if you still need logs & where I would specifically look to provide the part you need if you do. The console was only populating errors when trying to flip on a service without config.

**Comment by MFlyer** [comment]
Good morning @tastyratz , no more logs required, found problem and PR to solve this already on queue :)

Thanks
M.

**Comment by MFlyer** [comment]
Hi @tastyratz , can we close this?? last PR adding config modals added missing parts

M.

**Comment by tastyratz** [comment]
Hello,
I just updated, tested, and confirmed this resolved for myself after a cache reset. Closing bug.
Thanks guys!
