### ISSUE TITLE
Pool creation succeeds but refresh icon(ajax-loader) still exists

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-core#1563]
Even though the functionality works, the UX is bad because of the refresh icon.
Steps to reproduce:
1. The Icon starts rotation as soon as the user enters in the add pool view.
2. Fill up the fields and click submit. New Pool is created taking to the pools view.
3. The refresh icon still exists and goes away only when you refresh the page a couple of times.

Adding few snapshots to explain problem in better fashion.

Add pool View
![addpool_refreshicon](https://cloud.githubusercontent.com/assets/1999710/20819139/582b78ea-b7e7-11e6-8146-0d8decdae5d9.png)

Pools View
![pools_refreshicon](https://cloud.githubusercontent.com/assets/1999710/20819143/5c85b73e-b7e7-11e6-916f-7ab720612d06.png)

Console Error
![addpool_consoleerror](https://cloud.githubusercontent.com/assets/1999710/20819179/9893b5d2-b7e7-11e6-827b-a7876a3b36e4.png)

**Comment by phillxnet** [comment]
Had a quick look at this but unfortunately didn't get anyway. Only that it concerns the code added in:
pr #1460 but I don't think it's been happening since then, just the last few testing channel versions; although this is just from memory.

The indicated console error can be triggered by just clicking on the "Create Pool" button and is perfectly reproducible. Had a look as this is potentially holding up my own issues as it would be better for this to be error free prior to me making additional changes in this same area.

Any more pointers from anyone, seems like it's going to be something simple I'm just not seeing.

**Comment by MFlyer** [comment]
Hi @priyaganti @phillxnet & @schakrava ,
my 2 cents:
main error is that 404, because `'match' of null` raised by the xhr request failing with 404, that `api/pools/usage_bound?raid_level=single is wrong` url is wrong. @phillxnet any idea with the right url?
M.

**Comment by MFlyer** [comment]
Amend my last message, can confirm @phillxnet idea about #1460, while accessing create pool page got this on rockstor.log:
`[07/Dec/2016 14:03:55] ERROR [storageadmin.views.pool:470] Exception while updating disk state: 'PoolDetailView' object has no attribute '_update_disk_state'`

And finally found why we have this messy one:
aaa1963 and cafda50 flushed mods @sfranzen had over #1460

**Comment by phillxnet** [comment]
@MFlyer Well done and thanks for diving into this one, I am still pretty rubbish in this area and just didn't see it.

**Comment by MFlyer** [comment]
> and just didn't see it.
Once again @phillxnet , like on another recent issue, I was just lucky: while checking @sfranzen PR and my pools.py url file noticed missing rows ;)

**Comment by phillxnet** [comment]
@MFlyer I've just confirmed your fix here on my current dev branch by the way. Will update the pr with this.

I'm chuffed this is sorted; at least as far as the symptoms I've noticed are concerned.

@priyaganti It looks like @MFlyer 's patch also sorts the lingering refresh icon as well, at least from my test here.
