### ISSUE TITLE
[New feature] Add option to disable BTRFS quota/qgroups

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1592]
Qgroups seem to cause a lot of trouble / performance issues. Personally I get errors like `BTRFS warning (device sda): orphan qgroup relation 0x563->0x7df00000000000a`.
Picking up an idea from a [forum post by Matthew](https://forum.rockstor.com/t/somethings-broken-the-mounts/2241/8) it would be nice to be able to completely disable quota related functions in Rockstor.

**Comment by MFlyer** [comment]
Adding some note:
qgroups disabling -> no, helps getting pools & shares size
disabling quota limits -> possible

M.

**Comment by schakrava** [comment]
You both have good points here. Redesigning the quota stuff has been on my list for a while. I see that things have improved in 4.10, but it would be nice to give the option to cleanly disable them.

**Comment by phillxnet** [comment]
Linking to related pr #1867 where we at least don't block mounts when quota disabled.
And to in progress issue #1869 tallying remaining fail points when quotas are disabled.
The latter contains some info re Rockstor issues but focuses on why a quota enabled status was not maintained by a pool (unresolved and suspected to be quota anomaly in fs).

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
Final testing in progress. Pull request to follow shortly.

**Comment by phillxnet** [comment]
Inline edit of quotas Enabled / Disabled setting in Pool overview page:
![quota-inline-enable-disable](https://user-images.githubusercontent.com/2521585/36394910-4db4029e-15ae-11e8-84bc-d0e25a2a796d.png)

**Comment by phillxnet** [comment]
The code to address this issue is now ready, however as it interrelates closely with an existing and outstanding pull request I will await that pull requests review and potential merge prior to submitting the pull request for this issue.

Noting ideal dependency on prior merge of pr:

"empty compression setting on imported pools blocks extra mount options. Fixes #1896" pr #1899 

Once the outcome of the above referenced pull request is finalised I can, if then appropriate, re-base and submit the pr for this issue. This cautionary action is due to many very closely related changes made to the bootstrap inline editable UI code that could lead to merge difficulties if a re-base is not first performed.

**Comment by phillxnet** [comment]
This issue is again my main focus and will shortly be rebased, retested, and it's associated pull request submitted.

**Comment by phillxnet** [comment]
About to delete GitHub resident branch, re-base, and re-publish under the same branch name.

**Comment by schakrava** [comment]
Really thankful for the work you did on this @phillxnet !

**Comment by phillxnet** [comment]
@schakrava Thanks. Hopefully with ongoing quota work upstream this will in time become less of an issue going forward.
