### ISSUE TITLE
[Bug] Removed but not wiped device appears in pool again

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1612]
Steps:
1. Unplug a device (e.g. one of two RAID1 disks in a pool)
2. Delete in in UI (Storage - Disks) via Trash icon button
3. Plug it in again
4. Storage - Disks - Rescan

The device seems to be part of the pool again, but `btrfs fi sh /mnt2/mypool` does not known about this.
_[Edit]_ I guess the problem here is that the device still has the label "mypool" and Rockstor assumes that it belongs to the pool? Maybe the functions where Rockstor syncs it's DB with reality (i.e. BTRFS) is the place to look at?

**Comment by phillxnet** [comment]
This is a known behaviour and there are improvements to be made for sure. Currently I'm working on #1494 which is one layer lower than this, ie disk management. In that and some prior disk related issues the disk management has improved but soon I'm hoping to look more at the pool management and this issue can serve as a starting point for that.

At the moment for a few seconds after adding a pool we update the db info on the pool status from a simple btrfs command, then on the next disk rescan the sate of the disks is taken into account to inform the pool status from the disks perspective. There are issues with this but it's not a trivial problem as we need to reflect both and what we currently don't do is inform the user of discrepancies between the 2 perspectives. As you point out the disk view (via lsblk / udev) shows that disk to have a label and a file system that is consistent with it being a member of that pool, as at one point it was. And we must maintain a memory of that. When you delete the "detached-" disk you are not changing the btrfs perspective but the Rockstor knowledge of that device. This is confusing as it could be viewed that you are removing a btrfs missing device. When it is plugged back in (un alterred) there is only the disk info to go from and that suggests from label info that it belongs to the indicated pool. However as you see the btrfs fi show perspective is different. Hence we have the discrepancy. Essentially we work top down then bottom up but we need to do both and highlight differences as issues. I'm pretty sure we have the mechanisms in place to at least address this and what you are seeing is a bug where we aren't fully tying these mechanisms together and labelling or sensibly prioritising one over the other. Definitely a bug but needs very careful consideration as we need to account for a number of failure scenarios that aren't yet fully reported by the underlying technologies. Ie btrfs has no concept as yet of a 'bad' disk. This constrains our 'true' gathering (what we establish as datums) but I'm fairly sure our disk management is almost there. We just need to polish the pool management a tad and bring the 2 perspectives together in an informative and usefull way: especially in specific failure scenarios.

This is an important and clean report but we have to be careful we don't throw the baby out with the bath water on this one as there is the real chance for us to add an important 'appliance' level to our user feedback if we deal with this well. Else we might throw away some cool features that our independent memory of what was the case, and what appears to be the case from both disk and pool perspectives (as reported by 2 different mechanisms (udev vs btrfs)) brings to the table. Hence the importance recently of the finding that udev gets 'out of sync' with known truths in #1606. So you can see that we need to step carefully here and not over simplify the issue.

Thanks for reporting this issue so concisely and it is a known behaviour it's just potentially not as simple as it may seem. But we are definitely doing something wrong, I just want the fix to be the right fix in this case.

I'm personally interested in looking to this issue but I must first address my current issues backlog, some of which will help with this due to simplifications already in place in pending disk scan and  disk categorisation (roles) that may well lend themselves to an elegant approach to this issue. Ie labelling a disk with an 'inconsistent' role or the like in circumstances such as you have outlined: disk maintains filesystem and label that is inconsistent with a pools knowledge.

Thanks again as usual for you important input.

Also we have to note the mount capability / current status, of such a pool, ie btrfs missing devid's that restrict mount to degraded but only on first mount. All pretty tricky but doable in time.

**Comment by Hooverdan96** [comment]
@phillxnet, I assume that this is still in play despite our distro move and recent upgrades/changes?

**Comment by phillxnet** [comment]
@Hooverdan96 We have changed some of our disk management in the interim - and have had no further reports akin re failing to be bottom up, bar a cosmetic corner case concerning the system drive which is already issued in our current milestone.

Closing as both linked issues are now resolved.
