### ISSUE TITLE
[New Feature] Add Yum capabilities to System updates

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1619]
Hi @rockstor/developers ,
currently our Rockstor handles only Rockstor updates, firing alerts only on Rockstor updates, and users don't have any kind of alert and/or way to yum update from WebUI.

Decided to open this issue after recent yum updates solving major issues like samba & nss related

Mirko

**Comment by MFlyer** [comment]
Note about ab2d320, 839c8e2, 86cb21d : 

Tests with:
`yum downgrade -y wpa_supplicant` -> Blinking dashboard font awesome icon (4.7)
`yum update -y wpa_supplicant` -> dashboard icon hidden

Font Awesome note : change router.js icon to an old font awesome icon (ex. ban) to test till you get FA 4.7

Mirko

**Comment by MFlyer** [comment]
Hi @schakrava & @phillxnet ,
hope to close it by this week-end, but I'd like to have your opinions/suggestions:

Option A : 
suggest users to open "system shell" via WebUI or ssh and have yum updates

Option B : 
handle it all via WebUI and have yum updates from it with some frontend feedback (ex. like on log manager, live output from yum update)

Mirko

**Comment by phillxnet** [comment]
@MFlyer I favour Option B, however since we already have your rather nice log viewer in place could the user not be directed/linked towards that to view logs, ie less duplication and hopefully simpler; and possibly only if there was an error for example. Obviously a live progress of the update would be the business but maybe that could be added by way of another enhancement pr. Especially if you are looking to bring this to a conclusion.

Reverting to terminal for anything seems like a defeat of appliance nature.

**Comment by MFlyer** [comment]
On 59c1c47 we have some code I already had (and flushed while having some tests xD)

Starting with some screenshots:

Yum notification
![available updates](https://cloud.githubusercontent.com/assets/17988902/24586371/a606384e-179f-11e7-90cf-8a1a509c254b.jpg)

Yum packages modal with bootstrap accordion closed
![accordion closed](https://cloud.githubusercontent.com/assets/17988902/24586376/b7f74e3a-179f-11e7-905b-95af5bfec5ea.jpg)

Bootstrap accordion with package infos (name, changelog and description)
![accordion open](https://cloud.githubusercontent.com/assets/17988902/24586381/c7f34410-179f-11e7-9b01-ee2cdc79475b.jpg)
