### ISSUE TITLE
Disk wiping - force param required

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1698]
I think this is @phillxnet land ![notworthy](https://cloud.githubusercontent.com/assets/17988902/25314402/7131ee1a-2843-11e7-988e-ff5f6f770f84.gif), so won't work on it

While wiping some btrfs disks had different warning and finally had to `wipefs -a -f` from shell
@phillxnet sorry about no screens, this is just to say probably a `-f` param will always grant disk wiping

Mirko

**Comment by phillxnet** [comment]
@MFlyer Cheers, yes I can have a look at this some time. I have seen similar where a device is not properly unmounted, or otherwise held open some how, but after a reboot our regular "wipefs -a" was sufficient. Did you try a reboot in this instance? I'm a little reluctant to go all the way to 'force' if we can avoid it. Maybe all we need is additional guidance or a facility to help show and or clear rouge file handles or what ever else might be blocking our current "wipefs -a" on occasions.

Needs a little more digging really and a reproducer of course.

Thanks for opening this by the way, I should have done the same before.

**Comment by MFlyer** [comment]
Hi @phillxnet,
I had that "busy resource" because on pool folder via ssh while deleting it and I agree with you about carefully force disk wiping, but probably we should have an optional force checkbox like on shares/pools deletion box, do you agree? :)

Mirko

**Comment by phillxnet** [comment]
@MFlyer Yes I agree, mostly, as long as we also have additional Warnings / work-a-rounds when using this additional force feature as ultimately much better if we don't have to use it, plus I'm keen on keeping available options as minimal as possible. Also we haven't had any actual reports of this, other than ourselves that is. So I vote to leave this on the back-burner for the time being as the force option is itself a work around with big boots that will ultimately cover up problems that are probably best not covered.

I say we initially collect reproducers (such as your ssh open on pool) in this issue and first offer them up as reasons for failed wipe in the exception messages first. Lighter footed approach that way and less likely to stray into the force everything we can and end up covering up real issues or usability components that would otherwise be better addressed head on.

So initially I vote for no 'force' option as then too easy for users to directly resort to this and end up with surprises they weren't in a position to assess ahead of time: hence the richer exception messages suggestion as the initial 'fix' vector.

Delete / Wipe / Format / Key options are all to be handled with extra caution (obviously). In fact I think we need to back off a tad with our recent pool delete share approach that you site as example. I need to have more of a look to form my opinion properly on that one yet though.
