### ISSUE TITLE
[Dev env related]Luks - Missing cryptsetup under /usr/sbin

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-core#1723]
How to reproduce:
existing Rockstor system with no snapshots

Had to manually install cryptsetup via yum, ~but snapshots page is still empty / no available options~?!?

Mirko

**Comment by MFlyer** [comment]
Partially amending, snapshots page failing because of experiments with backbone :)
Solving missing cryptsetup dependency

Mirko

**Comment by MFlyer** [comment]
To @phillxnet & @schakrava : 
Noticed missing cryptsetup while having a buildout (dev env, not production!) and found we don't perform rpms anymore (https://github.com/rockstor/rockstor-core/commit/c579b5687e9c3688e9f3d50969cdcf0fafc4ba09#diff-a55fc4e553af13234f26342646b88e19), is that normal?!? Solved it via yum install cryptsetup
M.

**Comment by phillxnet** [comment]
@MFlyer Yes the cryptsetup package is now a hard dependency of the distributed rpm and has been since 3.9.0-1 rpm, see the now closed:
"add cryptsetup to preinstalled packages #14"
in rockstor-iso repo so that explains the not production bit.
Not sure of the plan re build system and rpms. I did add cryptsetup in: 
https://github.com/phillxnet/rockstor-core/commit/1a17d9de9ff841c437a64fa58a61541c8d4784c9
though.
I don't see the snapshots link in this issue though. Should the title be edited accordingly, ie to indicate dev env only issue as no effect on production release. Otherwise it looks like our prod LUKS is broken which I don't see.
I've taken to now uninstalling the rockstor rpm by hand when doing a dev build as a result of this rpm change.

**Comment by MFlyer** [comment]
Thanks for explanation @phillxnet ,got it on prod side
M.
