### ISSUE TITLE
Scheduled scrub throws error

### ISSUE THREAD

**Issue by kbogert** [rockstor/rockstor-core#1759]
Per: https://forum.rockstor.com/t/scheduled-scrub-throws-an-error/3448

The scheduled scrub tasks are failing due to use of the pool's name field instead of the ID.

**Comment by phillxnet** [comment]
Had a quick look into this earlier and my intention is to have another look later today. All progress will be noted in this issue.

**Comment by phillxnet** [comment]
Each scheduled task contains a json_meta field which is used by:
src/rockstor/scripts/scheduled_tasks/pool_scrub.py
to construct the API url.
Example contents of this json_meta field:
```
json_meta={u'pool': u'rockstor_rockstor'}
```
or via eg: https://rockdev.local/api/sm/tasks/ excerpt:
```
json_meta": "{\"pool\": \"rockstor_rockstor\"}
```
So we need to populate this json_meta field with pool id's rather than names.

**Comment by phillxnet** [comment]
@schakrava I have identified and linked to a duplicate report of this issue (#1762) and commented there on it's duplicate nature: indicating the 'awaiting review' status of the associated pull request (#1760).
