### ISSUE TITLE
Loose access to shares and have to reboot 45Drive.

### ISSUE THREAD

**Issue by rikker30** [rockstor/rockstor-core#1775]
I keep loosing my Samba shares. From Windows client you can read Data but I get access denied when I try to write.

Restart the device seems to fix it for a little while then it comes back.

**Comment by phillxnet** [comment]
@rikker30 Thanks for the report but due to the lack of reproducible context / detail this is more of a support request. You would be better off creating a post in our forum:

https://forum.rockstor.com/

and using the 'Troubleshooting' and or 'Support' Categories/Tags.
But given your report so far, and btrfs's tendency to go read only whenever it encounters a consistency issue, it would seem that this is what you are seeing: so the BTRFS Category/Tag would also be appropriate. Rockstor itself has no mechanism that auto remounts pools or shares with differing mount options; other than manually change the mount options of course. All can look OK after a reboot as the pool/share states are 'fresh' until a few writes / use patterns later the same issue is triggered and the ro remount ensues. Just a though.

Anyway many more eyes and a more appropriate arena await in the forum.
Also as of testing channel release version 3.9.1-3 Rockstor has improved WebUI reporting of currently active mount options so that may well help with diagnosing your current issue.

Hope that helps and that we see you on our friendly forum.

**Comment by schakrava** [comment]
Thanks @phillxnet
