### ISSUE TITLE
Rockstore installation diffear from documentation

### ISSUE THREAD

**Issue by sirio81** [rockstor/rockstor-core#1821]
Rockstore 3.9.1.
Installation process asks only to change root password.
This behavior is very different from what I can read in the documentation:
http://rockstor.com/docs/kvm_setup.html#vmmrockstorinstall

I also noticed it's not possible to select a keybord other than 'us'.

**Comment by sirio81** [comment]
Could you please report the hash of the iso on the download page?
md5sum of the iso I downloaded is: 66c08be577fb3d63edbf26c2ae11c96f.

I created a isohybrid by 
  isohybrid --uefi Rockstor-3.9.1.iso

When I use this modified iso, then I get the installer option.
I noticed anyway, while I was writing this post, that the installer started the installation process by itself.

I think it's important that the installer alway show up and don't start by itself installing the os.

**Comment by phillxnet** [comment]
@sirio81 Thanks for this issue report, would you mind moving it over to our (close this one and open a fresh issue) rockstor-iso repo as this is not related to the rockstor package but our included installer on the iso:
https://github.com/rockstor/rockstor-iso

Cheers.

We are due to 'rebase' our installer on the just released CenOS 7.4 so hopefully we can re-check these issues once that has taken place, the issue for this installer update is:

"Update the installer using latest CentOS 7.x #12":
https://github.com/rockstor/rockstor-iso/issues/12

The installers behaviour as is does seem to depend on hardware config and does, on occasions, show the expected config screen. Seems like we have an intermittent issue there but again good to look at this once we have updated the installer again.

Also best to keep each issue as focused as possible and search for existing issues in the relevant repo.

Thanks again for the testing and feedback on this. Also take a look at, and contribute if desired, to issue:

"support install with UEFI bios #5":
https://github.com/rockstor/rockstor-iso/issues/5

Also for documentation issues we have the following repo:
"rockstor-doc"
https://github.com/rockstor/rockstor-doc

However in this case it is the installer that is 'skipping a step' where it shouldn't so still rockstor-iso related.

Thanks.

**Comment by phillxnet** [comment]
@sirio81 Also note that we have in the same iso repo the following issue re the md5 / sha256 iso request:
MD5 #18
https://github.com/rockstor/rockstor-iso/issues/18
Please add your request to that issue as all contributions / requests can then be more easily seen re 'stuff' to get done.
Thanks.

**Comment by sirio81** [comment]
Thank you for your reply.

**Comment by phillxnet** [comment]
@sirio81 Thanks for helping to improve Rockstor.
