### ISSUE TITLE
disk serial is null

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1834]

**Comment by schakrava** [comment]
@phillxnet You'll be interested in this bug. My fix is probably needed but I am wondering if it's a symptom of something else. Wouldn't `do.serial` be set by then?

**Comment by phillxnet** [comment]
@schakrava Pretty sure what we have there is correct 'as is' and that code is just using the already established serial problem with a device (denoted by it's 'fake-serial-' beginning) to indicate that it would be futile to retrieve smart on something that we can't then track. But as you indicate do.serial should always be something (hence the fake allocation). So this is not the root of the issue and should never bee needed, plus there are many more serious ramifications with no serial, ie no by-id names and a potential db issues that we really don't want.

If a device has None for it's serial by then we have an earlier bug in:
scan_disks() in https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/system/osi.py
which tries really hard to get serial. First via lsblk, and then if no joy by udev. If both fail or there is found to be a 'repeat' we flag via the 'fake-serial-' generation. Everything from there on must have a serial, even if it's a fake one and many parts, even right through to UI handlebar elements, use the fake serial to denote an inability to track the device.

As such I think you are righ that this is an indication of a earlier problem (as indicated) and must be address there as otherwise we are just covering up here and will have to do the same in dozens of other places but will never actually resolve the issues as serial is paramount and, even if fake, must always be unique: which None is not.

Any more log info you can throw in here. Some devices just refuse to return anything or return useless info, this we must catch and re-label as fake-serial-uuid as per what is obviously bugged still (in the light of your report) in scan_disks(). I've done a tone of work on that procedure so it's pretty well documented.
We also have my old wiki on that area of the code:
https://forum.rockstor.com/t/device-management-in-rockstor/1768

So no we can't just tape over that do.serial being None as it's a serious issue where we fail to deal with it so there must be a bug in my serial retrieval in scan_disks() such that I don't account for something. Unless of course you have been hand editing the disk storageadmin_disk (you norty).

I did put in a final clause where I sanitise the db of 'bad things' which might be the place for such a check as you have done. That at least would give the system a change to self heal, assuming it ran into some anomaly that is now anchoring it in failure:

At the top of _update_disk_state() I do a final pass to guarantee we have no serial duplicates (which would be very bad and must never happen):

https://github.com/schakrava/rockstor-core/blob/2347b8f135cf8c4ef4eea8f0ffbacdf493cfba21/src/rockstor/storageadmin/views/disk.py#L94-L121

But all of this stuff has worked without issue for quite some time now I would would be very keen that we make no changes that are 'quick'. So I vote for looking at scan_disks() as that is the true cause of a null serial, but then if one exists in the db already (as if by magic) then the indicated emergency db sanitizer / sane make is our friend. But we will of course need an 'or' clause not an and clause and it will remove the db entry. But then at least there is a possibility for it to be re-added on next scan assuming scan_disks() is behaving better. 

So given the above I would say you attached patch is not what we are looking for. Serial is everything in the disk db and must be unique. If one is None another may also be None and then it will fail to update from there on at all, although that may have happened already: hence the suggestion to add to the sanitizer first sweep. 

I can have a look but would need a reproducer, more info. But all that code is extensively and completely commented now so should be possible to track where this None came from: baring the 'strange' anomaly effect of course :).

**Comment by phillxnet** [comment]
Linking to another suspected instance of do.serial having a None value as reported in the following forum thread:
https://forum.rockstor.com/t/unable-to-see-disks/4219

Awaiting more info from reporter in order to establish a reproducer as this should not be possible at this stage of the disk update mechanism.

**Comment by phillxnet** [comment]
I am currently looking again at disk_scan() and _update_disk_state() for issue #1866 and intend there after to attempt to re-produce this issue (if only by db editing) and see if we can't simply add it as a clause to the beginning of our _update_disk_state() pre-sanitizer to at least deal with those instances where it has occurred (for whatever reason). Obviously it would be better to identify the cause but that may come to light  on this or another examination and we at least have to deal with do.serial's that are already in this state anyway.

**Comment by phillxnet** [comment]
Both the original report of this issue, as indicated by proposed check for None, and linked forum thread, indicate an error with the second re.match of do.serial: around line 348. However during a test where an existing disk entry has it's serial set to NULL:

UPDATE storageadmin_disk SET serial = NULL WHERE name = 'virtio-serial-2';

It is the first instance of re.match (the initial sanitizer sweep) that is triggered similarly:
```
 File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 105, in _update_disk_state
    re.match('fake-serial-', do.serial) is not None):
  File "/usr/lib64/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```
This would suggest that _update_disk_state() is itself setting a NULL value or failing to set a value at all for a disk object's serial field: given NULL as default from storageadmin/models/disk.py. Or we are failing to pickup db updates with their Python counterparts.

So as yet no 'real' reproducer info.

**Comment by phillxnet** [comment]
I think we have a real world reproducer by way of forum member kingwavy in the following thread, using a 36 disk system. I have now reproduced locally, via a unit test based on kingwavy's submitted command outputs, an observe attribution of serial=None plus a lot of incorrectly attributed fake-serial attributions. Current suspected culprit detailed in:

"disk serial=none or fake-serial re sda[a-z] dev names" #1925 

Working on a fix against that issue.

Linking here to the referenced forum thread:
https://forum.rockstor.com/t/disk-scan-errors-expected-string-or-buffer/4783

I am currently of the opinion that we have a bug re large (sda[a-z]) dev names serial attribution / reporting in scan_disks() and am currently working on a solution.
