### ISSUE TITLE
XEN Installation - Not a valid BTRFS filesystem

### ISSUE THREAD

**Issue by agaver** [rockstor/rockstor-core#1856]
Hello there,
Getting this error when running on a XEN VM:
Error running a command. cmd = /sbin/btrfs filesystem show /dev/disk/by-id/xvda3. rc = 1. stdout = ['']. stderr = ['ERROR: not a valid btrfs filesystem: /dev/disk/by-id/xvda3', '']

 Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 377, in post
    return self._update_disk_state()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 322, in _update_disk_state
    p.uuid = btrfs_uuid(dob.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 1055, in btrfs_uuid
    [BTRFS, 'filesystem', 'show', '/dev/disk/by-id/%s' % disk])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 115, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /sbin/btrfs filesystem show /dev/disk/by-id/xvda3. rc = 1. stdout = ['']. stderr = ['ERROR: not a valid btrfs filesystem: /dev/disk/by-id/xvda3', '']

However these are my partitions:
[root@rockstor ~]# df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     3.9G     0  3.9G   0% /dev/shm
tmpfs          tmpfs     3.9G  8.5M  3.9G   1% /run
tmpfs          tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/xvda3     btrfs      18G  1.9G   16G  11% /                           <======
/dev/xvda3     btrfs      18G  1.9G   16G  11% /home
/dev/xvda1     ext4      477M  139M  310M  31% /boot
/dev/xvda3     btrfs      18G  1.9G   16G  11% /mnt2/rockstor
tmpfs          tmpfs     799M     0  799M   0% /run/user/0

**Comment by phillxnet** [comment]
@agaver Hello.
This issue is due to no disk serial being exposed by the Xen hypervisor through to Rockstor and hence udev has no way to generate the required by-id disks names.

Please see:
https://forum.rockstor.com/t/device-management-in-rockstor/1768

Resolve getting Xen generate unique serials for it's disks and udev can then make the required by-id disk names that Rockstor requires:
ie from our "Minimum system requirements":

"All drives must have unique serial numbers (real drives do); not all VM [*] systems default to this"
and:
"[*]	For VMware ensure you have disk.EnableUUID="true" in your .vmx file"

we welcome the appropriate [**] addition for Xen. We have yet to hear of a Xen configuration that can do this; or even if it is possible.

Linking to your comment in the following closed issue pertaining to no serial from a drive via VMWare:

"Having this issue when installing on a XenServer.
Any ideas?
Thx." in #545 

Please consider joining our forum where others may have ideas on how to persuade Xen to generate unique serials for it's disks:
https://forum.rockstor.com/

**Comment by agaver** [comment]
The workaround is for VMWare only.
Hope someone will find a solution to this.
Thank you for your answer Phillip.

**Comment by Airell** [comment]
I have the same issue, but unique UUID's are given in XEN. They are in the /dev/disk/by-uuid folder:

```
[root@rockstor disk]# cd /dev/disk/
[root@rockstor disk]# ll
drwxr-xr-x. 2 root root  60 Mar 21 06:55 by-id
drwxr-xr-x. 2 root root 100 Mar 21 06:55 by-uuid
[root@rockstor disk]# ls -la by-uuid/
lrwxrwxrwx. 1 root root  11 Mar 21 06:55 1cf434be-12a1-41e8-a47d-189414f023ce -> ../../xvdb1
lrwxrwxrwx. 1 root root  11 Mar 21 06:55 b50bf870-7391-46f6-a577-7ce9e46f0e18 -> ../../xvdb3
lrwxrwxrwx. 1 root root  11 Mar 21 06:55 ea26a1de-1127-4ad8-a3f2-41854ab9fa75 -> ../../xvdb2
```
I successfully passed the ("boot screen tab remove ks= parameter") issue, but I don't think you actually support XEN?

**Comment by Hooverdan96** [comment]
@phillxnet, @agaver, is this still an issue?

There seems to have been a successful go of it a while ago (albeit complicated):
https://forum.rockstor.com/t/software-raid-rockstor-os-failing-to-boot/4401

but I suspect this is still not resolved in a straightforward manner (since that issue still seemed to exist in 2021):
ttps://forum.rockstor.com/t/setting-up-rockstor-virtualized-on-xen/7607

**Comment by phillxnet** [comment]
Closing as Xen not an intended/supported platform:
