### ISSUE TITLE
Rockstor setup failed

### ISSUE THREAD

**Issue by gangshushu** [rockstor/rockstor-core#1919]
Hello, rockstor. When I finished rockstor's setting up and logged in to the browser, the rockstor initialization process failed. My rockstor's version is Rockstor-3.9.1.iso. I tried to use it in VMvare. Here is the error message:
  
  **Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 377, in post
    return self._update_disk_state()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 322, in _update_disk_state
    p.uuid = btrfs_uuid(dob.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 1055, in btrfs_uuid
    [BTRFS, 'filesystem', 'show', '/dev/disk/by-id/%s' % disk])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 115, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /sbin/btrfs filesystem show /dev/disk/by-id/sda3. rc = 1. stdout = ['']. stderr = ['ERROR: not a valid btrfs filesystem: /dev/disk/by-id/sda3', '']**

Best regards!

**Comment by phillxnet** [comment]
@gangshushu Thanks for the report.

This is due to the minimum system requirements not having been met. Please see our:

'Quick Start' doc section:
http://rockstor.com/docs/quickstart.html
and specifically the:

'Minimum system requirements' subsection: -
http://rockstor.com/docs/quickstart.html#minimum-system-requirements
it has instructions on how to resolve the no serial on disks default of VMware that causes this behaviour. Real hw has unique serials on it's disks and udev and consequently Rockstor depend on these serials.

The inelegance of this behaviour has been fixed but will only be evident once we release the next iso: as for non system disks we display a warning and link to the above docs which is obviously nicer than a straight up programmatic error.

Please consider joining our forum:
https://forum.rockstor.com/
where there are several reports and explanation of this current inelegance.

Hope that helps and thanks again for your report.

**Comment by gangshushu** [comment]
Ok got it. Thank you for your great effort.
