### ISSUE TITLE
Cannot delete a failed pool

### ISSUE THREAD

**Issue by T5-R** [rockstor/rockstor-core#1938]
For testing purposes I created a raid0 pool with 2 disks (+share and samba export). I then copies some data on it, later I removed one drive, and re-added it. I wanted to see if it is possible to recover the Pool/Raid0.
(seems impossible)
ThenI of course want to delete the useless failed pool, but I cannot remove the share:

```
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/share.py", line 337, in delete
    force=force)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 655, in remove_share
    run_command(chattr_cmd, log=True)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/bin/chattr -i /mnt2/raid0test/testshare. rc = 1. stdout = ['']. stderr = ['/usr/bin/chattr: Read-only file system while setting flags on /mnt2/raid0test/testshare', '']
```

So... you cannot recover the pool, you cannot delete it. How do I get rid of it? I am using 3.9.2-26 with stable updates.

**Comment by phillxnet** [comment]
@T5-R First off thanks for helping to support Rockstor's development.

"... later I removed one drive, and re-added it." Did you do this physically or via the Web-UI. Raid0 is not a redundant raid profile, half the data is on one drive and half on another: the pool size is then that of the combined drive size but it can't handle disk removal as then half the data is no longer there (when using the minimum drive count of 2 for raid0), much like removing half of a disk platter.

When btrfs notices a critical issue, such as you seem to have initiated, it generally goes Read-only, hence the inability to further change the volume (Pool) via the share delete:

" ... /usr/bin/chattr: Read-only file system while setting flags on /mnt2/raid0test/testshare' ..."
...
"So... you cannot recover the pool ..." it's raid0 so no redundancy, "... you cannot delete it." by design currently due to going Read-only when found to be degraded (missing disk) - btrfs default. Although as from 3.9.2-27 (available shortly) we have the following commented out line:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/fs/btrfs.py#L720

which is intended to allow the forced removal of read only subvolumes (shares). But in your case there is the likely hood that your entire pool is Read-only due to it's momentary degraded state (raid0 reduced to less than the minimum of 2 disks):

http://rockstor.com/docs/pools-btrfs.html#redundancy-profiles

You may well find that if you were to mount the pool 'rw,degraded' (Read Write Degraded) you would be able to effect a repair but note that it's a one shot deal currently, at least until we update our kernel (in the works). And due to the raid0 profile in effect you may end up with all changes / files copied (if any) during the disk absence and prior to the pool switching to Read-only being lost or damaged.

Essentially once a pool goes degraded it will no longer auto mount as rw, if you aks for rw. You are then required to enact a repair scenario which usually involves a degraded mount of some sort. Given you have no real data here you could just rw,degraded mount via Web-UI and delete and re-pave (via wipe rebuild. However given the disk is now returned you may well find that with a reboot it might be able to sort itself out (far more common with the redundant profiles such as raid1 though).

Btrfs currently falls a little short on dealing with live disk removal / re-attachment (there are improvements in the work), even with the redundant profiles. And as such can often only sort itself out on the next remount. I am far from a btrfs expert however hence my next suggestion.

Please consider joining our forum https://forum.rockstor.com/ as there are many more knowledgeable than I on btrfs behaviour / capabilities / repair/recovery scenario and mostly Rockstor sticks to current btrfs defaults. Oh and we have yet to implement Web-UI helpers in the form of repair wizards, but we do have a number of Web-UI alerts now in place, ie mount state reporting/ disk missing reporting etc.

I hope that helps and to see you on our forum for any and all contributions / suggestions you may have on how we might best approach some of our current Web-UI short falls.

Thanks for your report.

**Comment by T5-R** [comment]
@phillxnet 
Thanks for your response and clarification. 
I followed your suggestion on mountig with 'rw,degraded' and was able to delete it, Thanks!
I will look up the forum and join for further questions. 

Yes, I hot-unplugged it. I know Raid0 is not redundant, but since I am new to rockstor and btrfs I first want to check its behaviour to see what is best for me to use. Additionally I am not really much of a linux expert (more from the windows side) - even more reason to experiment before you use it.
Probably it is just a "mis-expectation" from my side, but the GUI inspires confidence that still is a bit lacking. I guess nothing you can't fix if you know the commands - which is where I'm lacking.

Anyways thanks for the quick reply.
