### ISSUE TITLE
ROCKON installation endless

### ISSUE THREAD

**Issue by Protten** [rockstor/rockstor-core#2002]
My installation of a Rockon has been indicating INSTALLING for several days. I have no way to cancel it, a reboot did not help either. What can I do. Many Thanks!

**Comment by FroggyFlox** [comment]
Hi @Protten ,

I've seen some docker containers hanging for obscure reasons so the issue you're having can result from a few different things. 

First thing first, I'd invite you to post your question on the forums ([https://forum.rockstor.com](https://forum.rockstor.com)) as you'll most likely get better chances to have your issue resolved due to the higher number of users there than here.

If and while you ask there, could you please provide slightly more details on your issue:
- What Rock-on is causing the problem?
- Is it the only one doing this?
- Can you install other Rock-ons?

We may be able to resolve the issue based on this information, but I feel we may have to wipe all traces of this Rock-on from Rockstor's database first before continuing troubleshooting. To do so, there is an undocumented script at your disposal, at described in [one of our forum threads](https://forum.rockstor.com/t/rock-on-stuck-in-loading-state/4546/4?u=flox):

```
/opt/rockstor/bin/delete-rockon

Delete metadata, containers and images of a Rock-on
	Usage: /opt/rockstor/bin/delete-rockon <rockon name>
```

Hope this helps, and again, I invite you to transfer this conversation to the [forum](https://forum.rockstor.com).

**Comment by Protten** [comment]
Hello, thank You for Your answer.


    What Rock-on is causing the problem? --> Ghost
    Is it the only one doing this? --> Yes
    Can you install other Rock-ons? --> No

![install](https://user-images.githubusercontent.com/45856200/49960682-09476180-ff11-11e8-9296-df3c8bde9a21.png)


Thank You!

**Comment by Protten** [comment]
The Script only brings an error, 

Traceback (most recent call last):                                                                                    
  File "/opt/rockstor/bin/delete-rockon", line 41, in <module>                                                        
    import scripts.rockon_delete                                                                                      
  File "/opt/rockstor/src/rockstor/scripts/__init__.py", line 5, in <module>                                          
    django.setup()                                                                                                    
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/__init__.py", line 17, in setup                             
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)                                                      
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 48, in __getattr__                  
    self._setup(name)                                                                                                 
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 44, in _setup                       
    self._wrapped = Settings(settings_module)                                                                         
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/conf/__init__.py", line 92, in __init__                     
    mod = importlib.import_module(self.SETTINGS_MODULE)                                                               
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module                                        
    __import__(name)                                                                                                  
ImportError: No module named settings

**Comment by Protten** [comment]
Hello, thank You for Your fast answer, now the INSTALLING rockon is gone.
But I can not install other rockons.


    What Rock-on is causing the problem? --> this was Ghost
    Is it the only one doing this? --> Yes
    Can you install other Rock-ons? --> No

Thank You

**Comment by Protten** [comment]
It works!

Thank You!
