### ISSUE TITLE
[openSUSE] shellinabox

### ISSUE THREAD

**Issue by flukejones** [rockstor/rockstor-core#2006]
`shellinabox` will need to be packaged. However:

1. It's most current release is a bit over two years old,
2. It uses openssl v1.0 (Tumbleweed defaults to 1.1)
3. Upstream doesn't include a systemd unit

So I'm wondering if there are better alternatives - but these must be written in systems languages, not for eg, python or node-js, these are just far too heavy-weight.

Fedora package source is [here](https://src.fedoraproject.org/cgit/rpms/shellinabox.git/tree/)

At this point I also suggest creating an _official_ rockstor account on [openSUSE OBS](https://build.opensuse.org/) to ease package building and supply, you should be able to get packages merged to official channels if required also.

**Comment by phillxnet** [comment]
@Luke-Nukem Nice find and point. I was wondering how we would do in this area.

As for official openSUSE OBS, yes agreed. But we don't really want to carry any special packages if we can help it. But may be unavoidable.

This feature was added by @MFlyer so mentioning here as he may have some input.

Over to project lead @schakrava for official rockstor account creation at openSUSE OBS. I'll revisit this task if we don't hear back shortly on this TODO:

**Comment by phillxnet** [comment]
@Luke-Nukem Maybe we should take your question:

"So I'm wondering if there are better alternatives ..."

onto the forum as we have more eyes there. I'm not up on what alternatives there are but hopefully others on the forum may be. Best if you could take a look at how @MFlyer implemented this so that you might judge if suggested replacements are viable. This is more in your area of expertise I believe so best if you ask: if you are game?

Linking to @MFlyer's pr that added our Web-UI shell capability:

"Issue#518 console access via web ui shellinabox" #1388

I expect that we can agree that carrying additional packages for our upstream is beyond our current 'crew' and best if we can resource something already there (in, or available for, our upstream distro already) and most importantly, currently developed, as all code tends to rot and if we need to move then so be it. We could always have conditionals using python-distro, as I've already started doing, to carry us over the transition phase to openSUSE. That way we can leave shellinabox specific code for the time being for our CentOS based subscribers while additionally adding what ever is to take it's place. Hey there might even be a Rust option out there :).

**Comment by FroggyFlox** [comment]
I came across a similar project today: **WeTTY** (MIT license)
https://github.com/butlerx/wetty

It seems to be based entirely on javascript:

> Terminal over HTTP and https. WeTTy is an alternative to ajaxterm and anyterm but much better than them because WeTTy uses xterm.js which is a full fledged implementation of terminal emulation written entirely in JavaScript. WeTTy uses websockets rather then Ajax and hence better response time.


Based on its documentation, it can be ran as a service, or even inside a docker container. It would add another js-lib dependency, however...

Just leaving this here in case it turns out being useful.

**Comment by FroggyFlox** [comment]
@phillxnet 

I was curious and had a quick look at the openSUSE repos and there seems to be a few non-official shellinabox packages: https://software.opensuse.org/package/shellinabox?search_term=shellinabox

The following one may be interesting, but we would need to add another repo...
https://build.opensuse.org/package/show/spins:invis:15:common/shellinabox

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for the pointers on this on.
I'm reluctant to use your highlighted repo as there are no Leap 15.2 builds (currently in beta) and no aarch64 but the single derived package from your highlighted repo looks more promising:

https://build.opensuse.org/package/show/home:Knurpht:Extras/shellinabox

Plus this repo's maintainer has an @opensuse.org email address.

**Comment by phillxnet** [comment]
@FroggyFlox OK, so if we drop the 15.2 availability with the hope it arrives in time, we also have a more direct drop-in replacement that includes a move to systemd & firewalld. Our other openSUSE options thus far have still used chkconfig and SuSEfirewall2 where as our shellinabox related code currently expects systemd capability.

Maintainer @suse.com with this time 2 other Users involved with the same repo.

So this one looks to be a little more official to me, and looks like it's appeared since you last looked.
https://build.opensuse.org/package/show/shells/shellinabox

**Comment by FroggyFlox** [comment]
Hi @phillxnet, and thanks for having a look at that one.

The second package you list seems really good, especially if it's a drop-in replacement! It actually seems like a perfect replacement if I understand correctly.

**Comment by phillxnet** [comment]
I am currently working on this issue.
