### ISSUE TITLE
data-collector service | can't turn off, service not shown, high cpu use

### ISSUE THREAD

**Issue by flukejones** [rockstor/rockstor-core#2007]
Using latest git master, the data-collector service was pegging my cpu at between 30-99%, and looked to be constantly respawning.

I was unable to find the service entry to turn it off, so had to rename the bin file.

---
Questions:

What is this service collecting?

What is it written in?

Are you open to optimizations by rewriting things such as this in another language (Rust is my preference here as it is fast, and will almost always be correct behaviour once compiled).

**Comment by phillxnet** [comment]
@Luke-Nukem I don't see this CPU pegging myself: however I also don't use single CPU as that is not realistically what Rockstor is likely to be deployed on, nor is such an architecture appropriate for a NAS especially one using btrfs (heavier cpu dependency than most other filesystems).

Also lets try and keep the re-write in X suggestions to a minimum at least until we have moved our thousands of Python lines from our existing legacy Python to Python 3.7 (see "move to python 3" #1877) which we now have less than a year to start and complete as that's probably enough to be getting along with for now language wise. Also Python before Rust in almost everything due to programmer base. You may be the only Rust coder among our current contributors. Nothing against it but we have to maintain each others code going forward and we already have quite enough languages / frameworks / libraries in this project already I say. Now if you could replace all the js: now we are talking :).

Optimisations always welcome of course and I have a significant number in the disk/pool scan realm awaiting the merge of our existing pull requests.

Lets have this issue as a 'tracker' for what was causing your high cpu use. Did you for instance pre apply the pending pr: 
"pin python-engineio to 2.3.2 as recent 3.0.0 update breaks gevent. Fixes #1995" #1996
as this has a bearing in that area I believe.

Thanks for the issue creation and in depth investigations by the way; and it would be great to know what your high cpu usage ends up being. And I'm fully in favour of making our code fast but not at the cost of maintainability / readability / portability else we would be writing in machine code (and mine is pretty rusty). But yes we have some sub optimal code for sure but best we address that peace meal once it's significant and actual origin is first established. Also we have several hundred outstanding issues relating to base functionality with few mentioning performance woes related to Rockstor's code.

Hope that helps and doesn't dis-wade you from anything you fancy having a go at as we are essentially a do-ocracy, but we also have to keep an eye on maintainability / sustainability. Also our Dashboard itself has only recently been re-written by @MFlyer.

See how you get on with applying that pr first before a fresh build and retest / reassess.

Our master branch is usually in better shape but that upstream change caught us out and appeared only hours after the last pr I think. Plus we have had a quiet time on the merge / releases side (looking into that).

**Comment by Luke-Nukem** [comment]
> I don't see this CPU pegging
I probably used the wrong term. I mean that it's hitting very high usage on whichever core it runs on which struck me as abnormal.

> lets try and keep the re-write in X suggestions to a minimum at least
Lol. I thought to myself afterwards "Oh, I've become one of _those_ people". I'll check out that Python 3 issue in the next few days. And if the replacement of JS is a serious thing, then I'll look at that also.

> "pin python-engineio to 2.3.2 as recent 3.0.0 update breaks gevent"
Didn't see this, I'll apply it soon. That would explain the missing elements, and I'm betting that _does_ have an impact on CPU use.

> nor is such an architecture appropriate for a NAS especially one using btrfs
I run Rockstor on an [AS3102T](https://www.asustor.com/en/product/AS3102T?p_id=44), it is running very very well so far, with Plex and Owncloud, plus Apple file sharing, and some of my experimental SAFE Network vault containers.
The point is that we should optimise as much as possible, because it's a good thing to do anyway. Being a systems programmer at heart means wasted resources or inefficiencies bug me :wink:

**Comment by Hooverdan96** [comment]
Considering that this is 4 years old, we've migrated to recent OpenSUSE versions, and are in the middle of a major overhaul of old librarise, django upgrades, do we need to keep this open as an issue, or can this be closed (and a new issue will be opened if this occurs again after the next release)?

**Comment by FroggyFlox** [comment]
@Hooverdan96, I completely agree. I'm thus closing this.
