### ISSUE TITLE
[openSUSE] docker start failure: recent Leap15.1 & Tumbleweed

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2032]
In more recent versions of openSUSE Tumbleweed the introduction of the "/etc/docker/daemon.json" file conflicts with our following docker wrapper command line:
```
--log-driver=journald
```
as the referenced file, added in newer Tumbleweed docker ce updates specifies it's own value for this option:
```
{
	"log-level": "warn",
	"log-driver": "json-file",
	"log-opts": {
		"max-size": "10m",
		"max-file": "5"
	}
}
```
resulting in the following system error:
"
'unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file:

log-driver: (from flag: journald, from file: json-file)
"

Harmonising these options seems not to help as it is that the options are in both places. 

By way of a work around prior to providing a fix for this situation developers / alpha testers are encouraged for the time being to rename this file to return prior expected behaviour:
```
sudo mv /etc/docker/daemon.json /etc/docker/daemon.json-backup
```
We need a consensus on how we deal with this situation and still maintain compatibility with ~~Leap 15.1 and hopefully also~~ CentOS, at least for the time being.

**Comment by FroggyFlox** [comment]
I now see the same thing in Leap15.1, unfortunately.
On the plus side, this means it'll make the fix easier as it just needs to be conditional to openSUSE and not just Tumbleweed.

**Comment by phillxnet** [comment]
@FroggyFlox Nice find and quite timely. Just as well they have now harmonised.

**Comment by Hooverdan96** [comment]
On a side note, the daemon.json file seems to come back with subsequent OpenSUSE updates, too. I had renamed it a week ago, and with the latest updates to the distro it showed up again (that might be normally expected, but I was surprised) - this was in Tumbleweed, which mostly is updated with the sudo zypper dup, and that might be the reason ... don't know enough about the package update process

**Comment by FroggyFlox** [comment]
Oh very good point, @Hooverdan96! I didn't think of that, but that makes a very compelling reason to rework our way of configuring the docker daemon. As you can read in #2088, I just started working on using the `daemon.json` file, and your point makes it even more needed. 

It also comforts me in using a separate json file (separate than `/etc/docker/daemon.json`) so that we don't risk having it overwritten by a package update. We'll follow the same idea of re-writing the config at the service start, anyway, so that mitigates this kind of risk.

Thanks a lot!
