### ISSUE TITLE
[Feature] Suspend/shutdown when certain devices are offline using scheduled tasks

### ISSUE THREAD

**Issue by p-betula-pendula** [rockstor/rockstor-core#2038]
I would like to be able to suspend/shutdown Rockstor using a scheduled task when my devices are offline – I am only using the NAS for a few hours daily and it seems unnecessary to me to let it run 24/7.

I guess the demand for such a feature isn't very high, so instead of waiting for it to possibly be added someday I would like to try to implement it myself. My experience with Python, Django and Javascript is quite limited, unfortunately.

Before I start, I'd like to know whether you agree with me on how to implement such a feature or whether you want it to be implemented at all.

My idea was to enhance the existing shutdown/suspend tasks by adding an option to scan for specific IP addresses and to abort if at least one device responds. A simple ping using ICMP and the `ping` command would be used and if no other device responds, another scan would be scheduled a few minutes later suspending or shutting down when there's still no response.

Intuitively I would put this feature side by side with the rtc wakeup feature and adapt the existing `reboot_shutdown.py` script in the backend. I would use the return code of the `ping` command to determine whether other devices are online, which according to the man pages is possible.

This would only cover a small subset of what other users might need, but to me it seems to be fairly easy to implement and useful nonetheless. It would work in local networks with fixed IP addresses and for normal devices only that are offline when not in use.

The user would be able to configure:
- the IP addresses to be scanned
- the interval between scans if no hosts are found
- how often to scan until the shutdown takes place

Any thoughts?

**Comment by phillxnet** [comment]
@p-betula-pendula This sounds like a really nice idea. The scheduled shutdown / wakeup stuff was added by @MFlyer in the following pr:

https://github.com/rockstor/rockstor-core/pull/1659

Linking in the hope that it might  help with your most welcome efforts. Keep in mind that quite a few bits of the code have been amended since then but code related to that feature is relatively unchanged.

Please see our **Developers** subsection of:
http://rockstor.com/docs/contribute.html
There are some formatting / CSS issue there but if you highlight the 'code' sections they show up OK. Doing some back-end stuff currently so should have that sorted in time.

Good luck and do consider joining our forum at:
https://forum.rockstor.com/
where you could also introduce your proposal to see if anyone chips in with further suggestions or hints on how this might appear within the Web-UI for instance. You could also link back to this issue from there for context.

Thanks in advance for anything you can do and please feel free to open further issue of anything you discover on the way. Forum is best for general dev questions and do please keep in mind that we are aiming a moving to an openSUSE base (Leap 15.1 / Tumbleweed) in the future but I don't see that bearing on your proposed feature.

**Comment by phillxnet** [comment]
@p-betula-pendula Linking to your recent followup forum thread for context:

https://forum.rockstor.com/t/suspend-shutdown-when-certain-devices-are-offline-using-scheduled-tasks-2038/6014

Thanks for posting your ideas there also. Much appreciated and also more likely to get non developer feedback there.
