### ISSUE TITLE
ARM architecture support?

### ISSUE THREAD

**Issue by polarathene** [rockstor/rockstor-core#2040]
Looking at some recent SBCs, they seem like they could make a nice small NAS system, but the Rockstor docs list 64-bit Intel/AMD x86 CPU as a requirement..

There is no issue raised here so far about ARM, and only some small questions about ARM support on the forums.

Is there any blockers preventing running Rockstor on ARM? Or is it just not officially supported? How likely is it that the ARM architecture may get support in future?

**Comment by phillxnet** [comment]
@polarathene Thanks for opening this issue. Yes I myself would very much like to see an ARM release and intended to put some time into this but it won't be for a while yet but we now have this issue in which to post progress. Won't be until we have transitioned fully to openSUSE though and then we can lean on their most excellent work, and long history, in this architecture.

I've been meaning to make such an issue / forum thread myself.

Please feel free to also open a forum thread on this, and link it back to this issue for context, as it would be interesting to see the community interest in this:
https://forum.rockstor.com/

**Comment by polarathene** [comment]
Done: https://forum.rockstor.com/t/arm-architecture/6036

**Comment by 20design** [comment]
Hello,

There are a lot of great SBC out there, especially the Rockpro64 who have a PCIE 4x slot which make it a perfect candidate for a small NAS. Hopefully it will be supported 🙂

**Comment by phillxnet** [comment]
@20design 

> There are a lot of great SBC out there

Agreed. We are not quite ready to extend out to AArch64 just yet but it is planned.
Please lend your voice to the linked forum thread where there are more Rockstor eyes as it may help to encourage this arch extension. I don't plan myself to tent to anything other than AArch64 however. Specific board mentions are also welcome, along with their associated arch and specification. It is also very likely that we are not going to entertain boards that don't carry host SATA ports. USB bus driven drives are just not suited to btrfs yet due to it's current failure modes and unreliability in the USB bus/drivers that agitate these current weak point in btrfs (i.e. intermittent & transient drive disconnect). But as you say, there are boards with proper SATA and the like now appearing.

**Comment by polarathene** [comment]
The issue with USB support is something that became more apparent to me with ODROID-N2(at least around it's release, not sure if they managed to resolve the issues), SBCs also had it worse if the USB drives weren't powered externally and relied on a stable supply from the board since it had a limited power budget to distribute iirc.

**Comment by phillxnet** [comment]
@polarathene @20design @rayfoss

I am delighted to be able to close this issue as we now have official AArm64 support as from version 3.9.2-60 'Built on openSUSE' variant only:

https://forum.rockstor.com/t/beta-built-on-opensuse-testing-channel-changelog/7097/5

There are still some outstanding issues with incompatible Rock-ons not being filtered or flagged as such but we have an issue open specifically to address this current short fall:

"[arm64] Discourage or prevent installation of Rockons that are not available on the machines architecture" #2191

And for an installer, and end to end testing, we also now have a Pi4 / Raspberry Pi 4, profile in our newly released "Rockstor 4 Installer Recipe" repo:

https://github.com/rockstor/rockstor-installer

Where we are inviting folks to test our installer recipe. The resulting Pi4 installer behaves exactly as the x86_64 installer except that is is not an ISO but an actual raw image intended for transferre to the target system microSD card itself. Rather than an ISO as per the x86_64 profiles.

Also note the following forum thread with regard to the installer, i.e. a call for beta testers of the installer:
https://forum.rockstor.com/t/rockstor-4-installer-recipe-call-for-beta-testers/7237

Which in the context of this issue relates specifically to the Pi4 profile. And please note that we are welcoming other Arm profiles as per the installers repo README.md. And we are hoping for a new Ten64 profile to be added by our new contributor @mcbridematt who was instrumental in encouraging us to add our first AArm64 profile (the Pi4), so that the Ten64 profile might be based on the work now presented for our first arm64 profile of the Pi4.



> ... until we have transitioned fully to openSUSE though and then we can lean on their most excellent work, and long history, in this architecture.

So in short this has now happened and we now only build rpms for our pending re-launch as "Rockstor 4 Build on openSUSE".

> I don't plan myself to tent to anything other than AArch64 however.

It is very unlikely that any non 64 bit architectures will be supported. And frankly, for the time being, very unlikely that we can entertain any non AArch64/arm64 targets at all really. But there are many examples of  boards/system on this architecture and many still require, like the Pi4 we already support, 'special' treatment. Hence the plan for each example to having it's own profile if it doesn't fit a yet-to-exist generic AArch64 profile.

Thanks to all those here and on the linked forum thread, which I will update shortly, for helping to usher in this new architecture support in Rockstor. And again thanks to @mcbridematt for already contributing towards our AArm64 compatibility to get us this far.
