### ISSUE TITLE
[Config Restore] Service status is not restored

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2087]
Although the configurations of services are included in the Config backups and restored accordingly, their **status** is not.

As we keep their status (ON/OFF) in `smart_manager`, it is in theory possible to include this information in the config backup and use it during restore so that all services in the backup that were configured AND turned on would also be turned back on after a config restore.

@phillxnet, do you think it's an idea worth pursuing or is the service status not restored on purpose?

**Comment by phillxnet** [comment]
> @phillxnet, do you think it's an idea worth pursuing or is the service status not restored on purpose?

Definitely, most likely the (ON/OFF) state was just due to the then early development state of the config save/restore feature. But as you've done a fair bit of work on it since then it may well be a workable extension. But we do have such things as the Rock-ons-root to restore of course and if that is not correct with say a different pool, but we default to fail over anyway.

Would be a nice to have if you think it's doable, given your more recent work in that area.

**Comment by FroggyFlox** [comment]
Sounds good!



> But we do have such things as the Rock-ons-root to restore of course and if that is not correct with say a different pool, but we default to fail over anyway.

That's already implemented. It's based on the share name, of course, but because it's intended to work after importing a disk (that's my understanding, at least), it works.



> (...) if you think it's doable, given your more recent work in that area

We already have the necessary api calls ready, I believe, so _in theory_ we could just trigger the required services if they have an ON status in the given backup. It's actually something I noticed while testing #2066 and having the service turned ON before is a requirement for #2066 to work. It would also respect what the user already had in the previous configuration so it would be nice to restore that as well.

I'll go on and work on a proof of concept, then, thanks!

**Comment by FroggyFlox** [comment]
I have now a working branch to fix this issue and will submit a PR "shortly".
