### ISSUE TITLE
Email alerts not sending on openSuse 3.9.2-57

### ISSUE THREAD

**Issue by meresda** [rockstor/rockstor-core#2165]
I have configured and tested the email alerts. However system notifications are being rejected by my email server because they are being sent from "root@localhost".

Full text of error;
`The "MAIL FROM" email address root@localhost / 550-localhost you are using
    is not hosted on this server. Tried to use 550-root@localhost / localhost
    as mail from address. Sending mails from 550-addresses not hosted on our
    server is not allowed. Please check the "MAIL 550-FROM" settings of your
    mail client and make sure you set the "MAIL FROM" 550 address to an email
    account which is hosted on the server.`

**Comment by phillxnet** [comment]
@meresda Thanks for the report. This one is curios though as we have only recently proved email notifications working for our Leap 'Build on openSUSE' rpm variants. This was last looked at in 3.9.2-54:
https://forum.rockstor.com/t/3-9-2-stable-channel-changelog/5741/21
via pull request: https://github.com/rockstor/rockstor-core/pull/2135
and no changes have happened in that area of the code since.

Could you confirm that you are configuring you email notifications as per the following Rockstor doc entry:
http://rockstor.com/docs/email_setup.html
From memory and that doc the "Email" entry in the Web-UI form should be the from address used in sending, hence the surprise with your 'From' being incorrect. Rockstor simply uses another email account to send it's email and logs into that provider/account to do the sending.

Double check your configuration to see if you have configured as per that doc and let us know how it goes, maybe there has been an upstream change in default config since then.

**Comment by meresda** [comment]
I can confirm that that I configured via the referenced document. The test email fires fine. I receive that no problem. It is subsequent system generated emails that fail. Here is a snip from the mail log. I replaced my personal email information with "external_host" and any IP addresses with XX

`2020-05-08T10:36:45.180112-04:00 165-backup postfix/pickup[24419]: 2BDAC1FD5DB: uid=0 from=<root>
2020-05-08T10:36:45.193475-04:00 165-backup postfix/cleanup[6960]: 2BDAC1FD5DB: message-id=<20200508143645.2BDAC1FD5DB@localhost>
2020-05-08T10:36:45.196336-04:00 165-backup postfix/qmgr[4850]: 2BDAC1FD5DB: from=<root@localhost>, size=5794, nrcpt=1 (queue active)
2020-05-08T10:36:45.212110-04:00 165-backup postfix/local[6962]: 2BDAC1FD5DB: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.05, delays=0.03/0.01/0/0, dsn=2.0.0, status=sent (del
ivered to mailbox)
2020-05-08T10:36:45.212836-04:00 165-backup postfix/cleanup[6960]: 333531FD5DC: message-id=<20200508143645.2BDAC1FD5DB@localhost>
2020-05-08T10:36:45.214069-04:00 165-backup postfix/local[6962]: 2BDAC1FD5DB: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.05, delays=0.03/0.01/0/0.01, dsn=2.0.0, status=sent (
forwarded as 333531FD5DC)
2020-05-08T10:36:45.214779-04:00 165-backup postfix/qmgr[4850]: 333531FD5DC: from=<root@localhost>, size=5914, nrcpt=1 (queue active)
2020-05-08T10:36:45.215293-04:00 165-backup postfix/qmgr[4850]: 2BDAC1FD5DB: removed
2020-05-08T10:36:45.743318-04:00 165-backup postfix/smtp[6963]: 333531FD5DC: to=<mike@external_host.com>, orig_to=<root>, relay=mail.external_host.com[XX.XX.XX.XX]:25, delay=0.53, dela
ys=0/0.04/0.4/0.09, dsn=5.0.0, status=bounced (host mail.external_host.com[XX.XX.XX.XX] said: 550-Sorry XX.XX.XX.XX. The "MAIL FROM" email address root@localhost / 550-localhost you
 are using is not hosted on this server. Tried to use 550-root@localhost / localhost as mail from address. Sending mails from 550-addresses not hosted on our server is not allowed. Please c
heck the "MAIL 550-FROM" settings of your mail client and make sure you set the "MAIL FROM" 550 address to an email account which is hosted on the server. (in reply to RCPT TO command))
`

**Comment by phillxnet** [comment]
@meresda OK, that great thanks.

Can you test to see if the email sent as per the pull request text command line test arrives or fails similarly:

"[openSUSE] fix postfix config re ipv4, tlsmgr, & CA file settings. Fixes #2132" #2135
i.e.:
```
# cli mail client already installed on our CentOS variants
zypper in mailx
echo "Body text of email alert" | mail -s "Alert Email" root
```
@FroggyFlox later in that same pull request also tested successfully a scheduler task email failure. Can you see if that works for you.

So it looks like some how the test email is working but the regular ones are not. Lets see if that command line email works or not.

I'm also assuming that you have setup your system as per 
https://forum.rockstor.com/t/built-on-opensuse-testing-channel-live-early-adopters-developers-only/6592
prior to the rpm install. Is that correct? I'm just wandering if some part of the config has been blocked by, for example, AppArmor.

Thanks again for helping to track this one down. Very curious.

**Comment by phillxnet** [comment]
@meresda On another note:
> 550-root

does this user/address relate to anything you have entered on the Web-UI?
I've not come across:

> 550-addresses

before.

**Comment by meresda** [comment]
I believe the 550 is a relay not permitted error. It is nothing that I have entered as part of an email address.

Using the mailx test, I get the same result. Except this time the error is `The "MAIL FROM" email address  /  you are using is 550-not hosted on this server.` Do I receive it  my root mail box. If I add the -r switch and enter my email address, the remote server accepts it.

I set up a scheduled task to fail. It did, but it didn't trigger an email. I see nothing in the mail log and there is nothing in the root mailbox. So it appears I have something else broken.

I did follow the install protocol. Apparmor is not loaded.
`# aa-status 
apparmor module is loaded.
0 profiles are loaded.
0 profiles are in enforce mode.
0 profiles are in complain mode.
0 processes have profiles defined.
0 processes are in enforce mode.
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.`

I also have done a zypper -f rockstor with no change. As well as deleting and re-adding my email information in the email alert section.

**Comment by FroggyFlox** [comment]
> I set up a scheduled task to fail. It did, but it didn't trigger an email. I see nothing in the mail log and there is nothing in the root mailbox. So it appears I have something else broken.

I just wanted to chip in on that one. I just tried the same thing before seeing your message and noticed the same behavior. I might have a idea on the cause, though, and have contacted @phillxnet to get his input.

**Comment by FroggyFlox** [comment]
In case this helps troubleshooting, here's what I have after fixing the little issue I mentioned above.

Upon creating conditions for a scheduled task to fail, the email is sent and correctly received. This was using a gmail address to send, and another gmail address to receive:
```
May 08 15:45:01 rockdev CRON[2520]: (root) CMD (/opt/build/bin/st-snapshot 2 \*-*-*-*-*-*)
May 08 15:45:01 rockdev CRON[2521]: (root) CMD (/opt/build//bin/st-pool-scrub 3 \*-*-*-*-*-*)
May 08 15:45:01 rockdev postfix/pickup[894]: E5B216E7C: uid=0 from=<sender.email@gmail.com>
May 08 15:45:01 rockdev postfix/cleanup[2565]: E5B216E7C: message-id=<20200508194501.E5B216E7C@localhost>
May 08 15:45:02 rockdev postfix/qmgr[895]: E5B216E7C: from=<sender.email@gmail.com>, size=1242, nrcpt=1 (queue active)
May 08 15:45:02 rockdev postfix/local[2572]: E5B216E7C: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.39, delays=0.28/0.05/0/0.06, dsn=2.0.0, status=sent (delivered to mailbox)
May 08 15:45:02 rockdev postfix/cleanup[2565]: 2C7F06E80: message-id=<20200508194501.E5B216E7C@localhost>
May 08 15:45:02 rockdev postfix/local[2572]: E5B216E7C: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.42, delays=0.28/0.05/0/0.09, dsn=2.0.0, status=sent (forwarded as 2C7F06E80)
May 08 15:45:02 rockdev postfix/qmgr[895]: 2C7F06E80: from=<sender.email@gmail.com>, size=1360, nrcpt=1 (queue active)
May 08 15:45:02 rockdev postfix/qmgr[895]: E5B216E7C: removed
May 08 15:45:04 rockdev postfix/smtp[2577]: 2C7F06E80: to=<recipient.email@gmail.com>, orig_to=<root>, relay=smtp.gmail.com[108.177.104.109]:587, delay=1.9, delays=0.14/0.06/0.73/1, dsn=2.0.0, status=sent (250 2.0.0 OK  1588967105 l89sm98108otc.32 - gsmtp)
May 08 15:45:04 rockdev postfix/qmgr[895]: 2C7F06E80: removed
```

Hope this helps,

**Comment by phillxnet** [comment]
@meresda Re:
> If I add the -r switch and enter my email address, the remote server accepts it.
This narrows it down a little. Thanks.

Some where we are failing to alias the root user for the intended user. The test email uses the give 'From email' but system emails, such as cron failures etc are from root to root I believe. Sorry getting late here. And so all that is reported here now points to an alias / forwarding of root error. 

@FroggyFlox Thanks for chipping in here that's really useful and it looks like have sorted at least one part of this. Can you confirm that with your changes you are able to successfully send the email as per the command line approach as then we know for sure that we do in fact have root email forwarding setup as intended?

I'm out of the loop for a few hours now as on UK time but the following is the relevant code for most of the email config:

https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/views/email_client.py

And the files that may not be as intended, after machine editing via the Web-UI, are likely:

ROOT_FORWARD = "/root/.forward"
GENERIC = "/etc/postfix/generic"

@meresda The main test we need to pass is that command line as all system errors are email to root (and from root I think) and as such we catch and redirect / forward / alias them to the entered To email and rewrite their from I think.

This could just be that openSUSE uses a different system user for from emails and we are just not catering for that different email.

Anyway I think we are close on this one so than @meresda and @FroggyFlox .

@FroggyFlox We have had a bit of an overlap here. Do you fancy bringing up your issue here as well as we may just, as you say in our other chat, be missing a program. But I wouldn't imagine it to be missing in a default openSUSE server install.

Sorry folks, bit of a muddled response. Got to dash as now fairly late.

@meresda Thanks again for this report and persevering with the testing.
@FroggyFlox I think you may have the answer to this one already. But the command line email send to root must work for us to pick-up all to-root emails and send them off as notifications.

**Comment by FroggyFlox** [comment]
Thanks a lot for the details, @phillxnet !

I'm sorry for all the messages, but postfix/email is completely unfamiliar to me :-( 

Here's what I have in journalctl after `echo "Body text of email alert" | mail -s "Alert Email" root`
```
May 08 16:23:47 rockdev postfix/pickup[894]: E39DC70BB: uid=0 from=<root>
May 08 16:23:47 rockdev postfix/cleanup[7317]: E39DC70BB: message-id=<20200508202347.E39DC70BB@localhost>
May 08 16:23:47 rockdev postfix/qmgr[895]: E39DC70BB: from=<root@localhost>, size=427, nrcpt=1 (queue active)
May 08 16:23:48 rockdev postfix/local[7319]: E39DC70BB: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.2, delays=0.17/0.01/0/0.02, dsn=2.0.0, status=sent (delivered to mailbox)
May 08 16:23:48 rockdev postfix/cleanup[7317]: F1F8970BC: message-id=<20200508202347.E39DC70BB@localhost>
May 08 16:23:48 rockdev postfix/local[7319]: E39DC70BB: to=<root@localhost>, orig_to=<root>, relay=local, delay=0.23, delays=0.17/0.01/0/0.05, dsn=2.0.0, status=sent (forwarded as F1F8970BC)
May 08 16:23:48 rockdev postfix/qmgr[895]: F1F8970BC: from=<root@localhost>, size=545, nrcpt=1 (queue active)
May 08 16:23:48 rockdev postfix/qmgr[895]: E39DC70BB: removed
May 08 16:23:49 rockdev postfix/smtp[7320]: F1F8970BC: to=<recipient.email@gmail.com>, orig_to=<root>, relay=smtp.gmail.com[173.194.223.109]:587, delay=1.8, delays=0.07/0.02/0.61/1.1, dsn=2.0.0, status=sent (250 2.0.0 OK  1588969431 v3sm640659ote.39 - gsmtp)
May 08 16:23:49 rockdev postfix/qmgr[895]: F1F8970BC: removed
^C
You have new mail in /var/spool/mail/root
```

And I did receive the email in my gmail inbox with the following main headers:

| Message ID  | <20200508202347.E39DC70BB@localhost>                    |
|-------------|---------------------------------------------------------|
| Created at: | Fri, May 8, 2020 at 4:23 PM (Delivered after 4 seconds) |
| From:       | root <sender.email@gmail.com>                           |
| To:         | root@localhost                                          |
| Subject:    | Alert Email                                             |
| SPF:        | PASS with IP XXX.XXX.XXX.XXX Learn more                 |
| DKIM:       | 'PASS' with domain gmail.com Learn more                 |
| DMARC:      | 'PASS' Learn more                                       |


The forward seems to be sent as expected:
```
rockdev:~ # cat /root/.forward 
recipient.email@gmail.com, root
```

**Comment by FroggyFlox** [comment]
@meresda, 

> I set up a scheduled task to fail. It did, but it didn't trigger an email. I see nothing in the mail log and there is nothing in the root mailbox. So it appears I have something else broken.

Following-up on that: would you report the output of the following?
```
zypper info cron cronie
```
I would be surprised to see these not included in your install, but I'd rather make sure of that.

Thanks!

**Comment by meresda** [comment]
Both are installed. I might not have been clear, but the task did run (and fail). It just didn't generate emails.
