### ISSUE TITLE
no update since 3.9.2-57 on centos repo

### ISSUE THREAD

**Issue by djslmft** [rockstor/rockstor-core#2190]
hey guys,

there's no update in the centos rockstor repo since 57. release, i there any issue or cause that you aren't updating that one?
did i miss smthg?

**Comment by StephenBrown2** [comment]
Yes, they are currently working on migrating to OpenSUSE, however the CentOS build is stable, and will remain supported at least until the built on OpenSUSE version is also stable.
https://forum.rockstor.com/t/rebasing-on-to-opensuse/5376 is the forum thread I've seen most often linked.
I see you've also posted [here](https://forum.rockstor.com/t/to-all-stable-channel-subscribers/6617/3), but I would recommend posting a new thread in the forums so that discussion can happen there. As 3.9.2-57 was [released 25th April 2020](https://forum.rockstor.com/t/3-9-2-stable-channel-changelog/5741/25?u=stephenbrown2), I wouldn't say you're behind very much if at all.

**Comment by djslmft** [comment]
thanks for the quick reply

i just don't wanna miss anything, i close the thread and waiting for the solution
