### ISSUE TITLE
Black formatting of python code

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2195]
Our python codes currently contains several inconsistencies in "style" that reduce code clarity and impede proper updates.

Recent pull requests have been including broad reformatting of their python code using the Black python code formatter:
https://black.readthedocs.io/en/stable/

I'm thus creating this issue to help keep track of such advances and promote a more widespread reformatting. Moreover, linking here to #1877 as the latter will be facilitated by such reformatting.

**Comment by FroggyFlox** [comment]
I am currently working on this issue.

**Comment by FroggyFlox** [comment]
@phillxnet , 

I'm nearing readiness for this work, but there were a few points I wanted to confirm/mention:

1. In a lot of cases, strings that were split in two lines are now combined into a single-line due to the higher character limit per line in Black. This results in a lot of cases as below:

**pre-formatting**
```
 params = {'<disk_name>': ('(optional)Print details of the given '
                                  'disk only'), }
```

**post-formatting**
```
params = {
            "<disk_name>": ("(optional)Print details of the given " "disk only"),
        }
```

As you can see, this creates an undesirable `" "`. I thus chose to manually remove these to end up with a clear string such as below:
```
params = {
            "<disk_name>": ("(optional)Print details of the given disk only"),
        }
```

2. Several files were left untouched:  

- all database migration files (storageadmin, smart_manager, or south_migrations): as these are automatically generated and not necessarily useful for the Python3 migration.
- `rest_framework_custom`: I was mostly unsure about that one, as to whether or not they were part of "third-party" libs that therefore shouldn't really be touched.
- `smart_manager/taplib`: same as above.
- unit test files

Let me know if that sounds good... A list of changes in the current related branch can be found below if interested:
https://github.com/rockstor/rockstor-core/compare/master...FroggyFlox:WIP_Black_formatting

**Comment by phillxnet** [comment]
@FroggyFlox That all sounds great; 'above and beyond' in fact. Nice tidy on split stings in brackets there.

This should leave us with only code function, rather than formatting, patches from now on which is a major relief on the review process. It's been quite trying, trying to intergrate black formatting 'as-we-go' and has made the pull request preparation and review more difficult than it already is. So well done stepping up to this rather massive and appreciable potentially tedious task. We should, post merge, then add black formatting as a pre-requisite of pull request submission to help keep the formatting in check.

We can double check the changed files list once it's in pull request form, but given black does a pre/post byte code check we should be OK.

Thanks again for all your efforts.
