### ISSUE TITLE
Minio S3 Storage

### ISSUE THREAD

**Issue by idnovic** [rockstor/rockstor-core#2218]
Please integrate Minio as network storage at the same level as the nfs and samba integration to provide S3 compatible storage. 

https://github.com/minio/minio

**Comment by phillxnet** [comment]
@idnovic Yes that might be nice. In the mean time we do have a pending pull request in our Rock-ons repo that provides this service. See:

https://github.com/rockstor/rockon-registry/pull/232

Sorry to @MikeMcPherson for our delay in getting around to merging this. There is even an accompanying doc pull request, again awaiting our setting up a new backend part ci/cd system helper.

https://github.com/rockstor/rockstor-doc/pull/245

@idnovic If you fancy double checking that Rock-on pull request we have the following form thread on how to go about this:

https://forum.rockstor.com/t/how-to-test-a-rock-on-pull-request/5224

Pretty sure @FroggyFlox has mostly now reviewed that pr and we are just awaiting the completion of our new backend work to use this 'safe' looking pull request to test it's function.

Thanks again for contributing this issue. Although best if you open a forum thread so others can chip in as there are more eye in the forum (at least existing rockstor user eyes) than here in our GitHub issues. We can then assess if the idea gets any traction and use the degree of support or otherwise to help prioritise this. Although if you fancy having a go at this yourself that definitely helps with it happening at all :). You could look to how our existing services work and mirror the most actively maintained of those (smb) to see if a default upstream included package in Leap 15.2 serves this purpose.

Until then it's the Rock-on route and it may be that keeping our 'core' services to an absolute minimum would server most folks better anyway. Again forum interaction on this is a good way to work out what the consensus is. We are predominantly lead by community contribution and requests. Bar our pending tec debt efforts of course which are often less obvious to the majority of users.

If you do open a forum thread on this topic, could you provide your reasons for favouring core inclusion over Rock-on. But keep in mind that we must, for our core services, use only Leap 15.2 and-on included services. See our rockstor-installer repo for our assumed default repos.

Cheers.

**Comment by idnovic** [comment]
Thank you. I did search for minio but was not presented with the issue on the rockon-registry

**Comment by FroggyFlox** [comment]
Hi @idnovic ,

In case you are still interested, I just wanted to let you know that the MinIO rock-on (https://github.com/rockstor/rockon-registry/pull/232) is now published so you should see it in your list of available rock-ons after clicking on the "Update" button in the top right corner.
