### ISSUE TITLE
Idea: Base web-ui on cockpit project

### ISSUE THREAD

**Issue by idnovic** [rockstor/rockstor-core#2219]
I recently read that nethserver started to port their ui to cockpit instead of keeping their own.

[netherserver-cockpit](https://github.com/NethServer/nethserver-cockpit)
They integrate the old ui parts as plugins into cockpit. 
I very much like the cockpit project.

Is this something rockstor as project would be interested in?
From a license standpoint I would even be allowed to base my work on their port. 
Because that is something I would be able to work on. 

I see the following improvements:
-base ui (cockpit) is taken care of by the cockpit project
-familiar base interface for a bunch of different servers
-more time for backend

Disadvantages:
-it is possible that not every part of the current rockstor ui is portable (much refactoring)

**Comment by idnovic** [comment]
I will create a forum thread later.

**Comment by phillxnet** [comment]
> Is this something rockstor as project would be interested in?

No not really. It's been years of work to get to where we are. Also note that we are Django based and our Web-UI is highly intergrated into our Django Python backend. Although folks could, if they wished and had the appropriate skill, create, using our API's, a plugin to cockpit. Which incidentally I was also impressed with. But we are very definitely an appliance. Cockpit is general use stuff and uses very different technologies to us as I understand it.

We are also GPLv3.

Note also that openSUSE already has yast. So our first port of call would be to become a better partner to yast than we currently our, given our CentOS roots. See:

https://forum.rockstor.com/t/built-on-opensuse-dev-notes-and-status/5662

Where currently if one uses yast (not currently installed by default due to incompatibility) and configures samba for instance, there is breakage around just how we comment our config files. So should be an easy fix but again in need of developer attention.

> -more time for backend

Rockstor is actually predominantly front end. We simply read and manage btrfs vol(pools)/sub-vol(shares)/snapshots and some basic services and user management. The backend for all of this is our home distro, mostly.

Rockstor is firmly aimed at an appliance ordinance. We are not an add-on but a purpose build disto that is basically a Web-UI to btrfs and a purposefully limited coverage to both. This keeps things simple and cockpit is not simple given it's a cover-all. That is not current aim as I read it from our community. Also not that we have many users who are already familiar with our existing Web-UI and converting the 10,000 of lines that run that Web-UI to anther system will be non trivial. Take a look at source code to get an idea of how we function currently. It may be that your efforts would be better placed in writing a btrfs layer for cockpit, if one does not already exist. The main appeal of Rockstor as I see it is a tool for the job, focused and simple. We are not a tool for all jobs which is the aim of such things as yast and cockpit. If folks want to use yast and cockpit they need go no further than the base distro. Where as our 'custom' purposefully focused NAS Web-UI attempts to be a specific tool for the NAS ordience. Not those who can already use the likes of yast and cockpit. Although we have a goodly number of folks who still prefer our Web-UI for what it was intended to do. Make stuff simple within a limited scope. Covering for example the entire gamut of just btrfs's capabilities is likely not to be something our Web-UI will every accomplish. But if we cover the main capabilities we can more easily maintain a simple Web-UI. But this of course remains to be seen.

Also keep in mind that all open source projects ultimately have to achieve sustainability in the medium to long term. Our sustainability model revolves around our Stable Channel subscriptions. What you are proposing is really a btrfs extension to cockpit, which if you look may well even already exist. I'm fairly out of date with cockpit myself given it's RedHat/fedora focus and our openSUSE focus. Also note the lack of upstream support within fedora/RedHat for btrfs. Contrasted with openSUSE's years long default use at least on the system drive (boot to snapshot etc).

Look forward to your forum post on this.

However I'm included to close this issue as it is in my mind, as the current maintainer, beyond the scope of our project as it stands and so I am unlikely to merge any rockstor-core contributions to this end. And those contributions, given your sketch, would very much seem like they belong to the cockpit project and not this one. And given their different 'homes' they are also not that likely to receive those 'rockstor' specific additions either. However if there is yet to be a btrfs plugin to cockpit (which I would be surprised at) then your contributions to cockpit could take the form of duplicating all the years of effort in this project within cockpit. That may or may not be feasible depending on your resources and if you manage to attract enough mind share on the effort. But you are of course welcome to broach the idea on the forum where there are already many btrfs users. But you should be clear on your exact intention here. And really you time may be better spend on a cockpit forum presenting your btrfs plugin ideas there. If that plugin / capability is not already there.

Interesting Idea though. We have also had something similar floated re ditching our own Rock-on interface for other docker manager interfaces. I in fact also proposed we ditch our dashboard for a dashboard specific project. But creating an intergrated user experience is easier said than done and often involves seemingly re-inventing the wheel when in fact you are creating your own take on what others specialise in. An a generic linux distro, which is not appliance orientated, is actually just that. Including for example a variety of desktops and systems management options. Rockstor is kind of an appliance take on these as are many appliance orientated distros.

Hope that helps, at least with my take on this currently.

**Comment by idnovic** [comment]
Well cockpit does have a storage plugin but no btrfs as far as I know. I do understand your viewpoint on this. And I do not plan on doing work which is not required.
