### ISSUE TITLE
Add .beeshome to the list of ignored subvolumes

### ISSUE THREAD

**Issue by ubenmackin** [rockstor/rockstor-core#2223]
See discussion here:

https://forum.rockstor.com/t/bees-beeshome-subvolume-getting-remounted-by-rockstor/7355/2

The gist is that I am requesting that .beeshome be added to the list of ignored subvolumes.

**Comment by phillxnet** [comment]
I am currently working on this issue.

Given we are likely to encounter other uses for a system-wide subvolume exclusion mechanism I'll use this issue to add a generic hard-wired system such as we already have for our system pool, but for all pools. Our existing system pool subvol blacklist is intended to mask subvols associated with a default openSUSE Leap install, such as for example the /var subvol. Where as I see the required mechanism here as one that might be used to mask 'after market'/non-native subvols, such as the indicated ".beeshome" one.

This subvol exclusion mechanism is important as a means by which we can remove incompatibilities that might otherwise hinder or break Rockstor's presentation of the imported pool states. Given non native subvols may well not comply to Rockstor's own expected subvol hierarchy/placement.

**Comment by phillxnet** [comment]
Linking for context with the prior root only subvol exclusion issue:
"add root subvol exclusion mechanism" #1931
and the associated pull request:
"add root subvol exclusion mechanism. Fixes #1931" #1935
