### ISSUE TITLE
Netdata RockOn install fails after Rockstor update ver 4.0.4

### ISSUE THREAD

**Issue by tlc-at-home** [rockstor/rockstor-core#2229]
I've had Netdata Rockon working well for a couple of weeks. Then, last night, I updated Rockstor to 4.0.4.
Then I found out that Netdata docker was no longer working. So I tried to fix it by uninstalling and reinstalling it. That failed with error message:
CommandException: Error running a command. cmd = /usr/bin/docker run -d --restart=unless-stopped --name netdata -v /mnt2/Rockon:/etc/netdata/override -v /etc/localtime:/etc/localtime:ro -p 19999:19999/tcp -p 19999:19999/udp -v /sys:/host/sys:ro -v /proc:/host/proc:ro -v /var/run/docker.sock:/var/run/docker.sock --net=host --cap-add=SYS_PTRACE titpetric/netdata:latest. rc = 127. stdout = ['']. stderr = ['/usr/bin/docker: Error response from daemon: stat 
 mnt2/Rockon/btrfs/subvolumes/727b5428579239334d532c751bb8cead93a91e6b5ac5f035c703610041cdb5eb: no such file or directory.', "See '/usr/bin/docker run --help'.", '']

**Comment by FroggyFlox** [comment]
Hi @tlc-at-home ,

Thank you for your report. I'm not 100% sure of what happened exactly there but it seems you have an issue with the container files themselves: `mnt2/Rockon/btrfs/subvolumes/727b5428579239334d532c751bb8cead93a91e6b5ac5f035c703610041cdb5eb: no such file or directory.`. Indeed, this btrfs subvolume represents one of the layers that constitute a docker container image. In your case, it appears that this layer is not longer available. I'm not sure why that is, but it could happen for a variety of reasons; note that we would need to know if the machine has been rebooted, or anything else that might have happened in order to know that.

Do not worry, though, as these docker containers are by design disposable, which means you can easily get things back in order. The inconvenient, is that you will most likely need to reset your rockons-root folder, which means you will need to uninstall and reinstall any rock-on you may have installed alongside Netdata. You do not specify whether or not you have other rock-ons installed and whether or not you have issues with those, but if you do have other rock-ons installed, I would suspect them to be problematic as well due to the fact that something seems to have happened to your rock-ons root (and thus affecting potentially all rock-ons). 

The procedure would be as follows:
1. Ensure all rock-ons are off and uninstalled.
2. Click on Storage > Shares, and click on the share used as rockons-root ("Rockon") to go to its details page.
3. Under the snapshot tab, delete all snapshots you see in this share.
4. Click on the Delete button in the top right to delete the share.
5. Recreate a new share to be used as rockons-root (can be any name, including the same as before).
6. Go to "Services" and configure the rock-ons service to use the share created in step 5 by clicking on the little wrench icon.
7. Start the Rockons service.
8. Reinstall any rock-on you had installed before, using the same shares that were previously used for them. This way you will be back in the same state as before.

Note, however, that I can see something that I would strongly recommend to avoid; it might actually have to do with the issue you're experiencing, actually. Indeed, we can see that your "rockons-root" share used to stored docker-related configuration, images, and containers is the share named "Rockon": `mnt2/Rockon/btrfs/subvolumes/727b5428579239334d532c751bb8cead93a91e6b5ac5f035c703610041cdb5eb`
At the same time, we can also see that the same share was used to store the netdata configuration file: `-v /mnt2/Rockon:/etc/netdata/override`. As this is very likely to create severe conflict between rock-ons and between rock-ons and Rockstor, we strongly recommend users to create dedicated shares to use for each rock-on's volume. In Netdata example, we thus recommend to create a dedicated share (named for instance "netdata-conf") to be selected during Netdata installation wizard.

You will find more information on all of this alongside examples in our documentation: http://rockstor.com/docs/docker-based-rock-ons/overview.html

Finally, note that I would recommend you to post any other issue you may have in our friendly forum (https://forum.rockstor.com/) as this is our preferred medium for this kind of things (you will get more feedback and will likely find the solution in previous threads).

Hope this helps,

**Comment by tlc-at-home** [comment]
I followed the suggested steps and I got all my Rockons working again. The only problem I had was in step 4 were want to delete the share. There is no delete button as this share was created by the Rockstor install process. So I created another share called Rockon-root and then set the Rockon service to use that. But now I have this share that will never be used. How do I clean that up?
Tony

**Comment by FroggyFlox** [comment]
>  There is no delete button as this share was created by the Rockstor install process.

This means you are trying to delete a system share, which would break your system; that's why Rockstor will prevent you from doing so. I'm unsure of which share you are referring to, but if Rockstor prevents you from deleting it, then it's for a good reason and shouldn't be deleted. It is most likely used by the system, for instance. I believe old version of Rockstor still surfaced one of these, but I can't remember for sure. Either way, I would leave it as is.

Make sure to have a look at our forum as you will most likely find useful information there and don't hesitate to ask there if you have any additional question. It would also allow you to show screenshot for instance when needed so that others can have a better idea of your situation.

Hope this helps!
