### ISSUE TITLE
Repeated Log Errors for shares with disabled quotas

### ISSUE THREAD

**Issue by GeoffAd** [rockstor/rockstor-core#2236]
Probably just a bit of LOG housekeeping really, but currently shares with quotas disabled are being repeatedly logged as Errors.  Example extract from Rockstor Log:

[16/Dec/2020 18:27:33] ERROR [system.osi:174] non-zero code(1) returned by command: ['/usr/sbin/btrfs', 'qgroup', 'show', '/mnt2/ROOT/home']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']

Logs are repeatedly filled with this 'ERROR', which isn't an error as ROOT pool share quotas are disabled by default, and other non-ROOT share quotas might also be disabled by user.  This information could be of use at times when tracking down other errors, so could these items be managed separately as DEBUG to avoid unnecessary filling of logs?

**Comment by phillxnet** [comment]
@GeoffAd  Thanks for creating this issue.
Re:
> as ROOT pool share quotas are disabled by default

This is not generally the case but can end up being so if one uses the system pool (named 'ROOT' in v4 onwards) due to dockers unwarranted interaction with quotas on occasions.
See:
"docker-ce dictating pool quota enabled disabled status"
https://github.com/rockstor/rockstor-core/issues/1906
for some background and a link to an upstream issue link.

I also think we have a quota disabled issue on some imports of data pools but haven't pinned that one down yet.

But whatever, your main issue here stands. We shouldn't any longer consider quotas disabled as an error. But it used to be so this is just a bit of our history showing through.

Thanks again for creating this issue. Much appreciated.

**Comment by phillxnet** [comment]
I am currently working on this issue.,

**Comment by phillxnet** [comment]
Linking for context to the forum origin of this issue:
https://forum.rockstor.com/t/repeated-qgroup-error-in-rockstor-log/7505

**Comment by GeoffAd** [comment]
Excellent stuff, thanks @phillxnet
