### ISSUE TITLE
Disabling Rockons service breaks Rockons UI page post rocknet config

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2239]
Post merge of pr "Implement docker networks. Fixes #1982." #2207 (4.0.5-0) we have a failure to check if docker is first enabled prior to attempting to query docker for rocknets purposes. This leads to the following error within the Web-UI on some pages (Rock-ons currently known):

['Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?', '']

Work around is to re-enable the Rock-ons service via the services page.

Thanks to @FroggyFlox for helping to narrow down this issue thus far.

Currently this issue is only associated with Rockstor version 4.0.5 (Release candidate 6).

**Comment by FroggyFlox** [comment]
Thanks a lot for clearly laying out this issue, @phillxnet.
I'll try to get to it as soon as I can.

**Comment by FroggyFlox** [comment]
Problem has been identified:
https://github.com/rockstor/rockstor-core/blob/1223360a17408e78808af238ed18aa044139c9d2/src/rockstor/system/docker.py#L152-L153

This shouldn't include the `running_filters`. We should thus remove these but I will need to make sure this doesn't break the other uses for this function. That also highlights the lack of corresponding unit tests, @phillxnet ... I'll try to see if I can remedy to that as well, but that is likely to take a bit more time, unfortunately.

**Comment by phillxnet** [comment]
> One shouldn't be able to customize Networking settings for a rock-on using host networking

Oh yes, I completely forgot about that one. Do you fancy making an additional issue for that?

**Comment by phillxnet** [comment]
> unfortunately been broken somewhere during my rebase

Yes, that my fault I'm afraid; in taking so long to tend to the rocknets pull request I appreciate that you had to rebase a number of times.
But at least it's in now :).

**Comment by FroggyFlox** [comment]
@phillxnet , sorry for the lack of focus on my previous comment... I've created a dedicated issue for that.

With regards to the current issue, there actually are a few points that are either broken (the one you described), or for which the error surfaced to the user could be more explicit when the Rock-on service is **not** running. I'll list them below and update as I find more (if any):
1. Creating a new rocknet from *System* > *Network*: errors out with the docker error surfaced to the user:
```
CommandException: Error running a command. cmd = /usr/bin/docker network list --format {{.Name}}. rc = 1. stdout = ['']. stderr = ['Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?', '']
```
This could be further improved to specifically tell the user to check whether the **Rock-on** service is turned on.

2. The same error as in point 1 above occurs when trying to edit an existing rocknet. Here, we might want to disable the "Edit" pencil icon directly (with a tooltip explaining why), rather than surfacing an error to the user. This would also greatly simplify the back-end logic.

3. Visiting the *System* > *Network* page throws the old unknown ctype: bridge error in the logs even though we know deal with these connections. This is because the logic behind that is expecting the Rock-on service to be ON. We could simply change the level in the logs, though, from `logger.error()` to `logger.info()` as this isn't really an error strictly speaking.
