### ISSUE TITLE
Enabling AD service prior to samba service gives unhelpful error 

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2241]
Thanks to @FroggyFlox for highlighting this issue. When the AD service is enabled prior to a configuration having been entered for samba, i.e. samba service disabled and not having been enabled previously, the following inelegant and unfriendly error message is displayed:

> Traceback (most recent call last):
>   File "/opt/rockstor-dev/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
>     yield
>   File "/opt/rockstor-dev/src/rockstor/smart_manager/views/active_directory.py", line 125, in post
>     smb_config = self._get_config(smbo)
>   File "/opt/rockstor-dev/src/rockstor/smart_manager/views/base_service.py", line 43, in _get_config
>     return json.loads(service.config)
>   File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> TypeError: expected string or buffer

This is thought to be down to an empty samba config.

Workaround: Configure/enable samba prior to AD enablement.

**Comment by FroggyFlox** [comment]
@phillxnet, I'm currently working on this issue.

I'm actually thinking of going one step further than just surfacing a more explicit error message: doing the fix for the user.

In brief, here's what we're **currently** doing here:
1. get the `smb` service config from the database
2. get the value to be used for Samba Workgroup from the AD REALM (fetched directly from the AD server)
3. Trigger the process leading to the update of `smb.conf` with AD-specific values, and the workgroup fetched at step 2.
4. Restart all samba-related services (and SSSD, of course).

Now, we can clearly see why we're currently failing if the `smb` service has not been configured by the user yet: step 1 fails. Instead of just failing, we could add this config value to the `smb` service db entry as we are automatically fetching this value in step 2 above.

This would represent a nice quality-of-life improvement as we pretty much remove one step needed to join an AD from Rockstor.

Where we can create some problem with this approach, however, is if the `smb` is already configured to use a workgroup different than the one needed to join the AD realm. In this case, we would overwrite what the user already has setup (and possibly running). While this may be what the user wants in some case, this might not be in others; in which cases we are silently undoing the user's previous work on its `smb` service configuration.

I thus see two options here:
- option A: we still force the overwrite of the `smb` workgroup to ensure AD is working properly.
- option B: we raise an Exception and inform the user that there is an incompatibility in workgroup setting requiring the user to make a decision (and brief instructions on what to do).

What do you think?

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for picking this one up. Much appreciated.

> What do you think?

I vote for:

> * option B: we raise an Exception and inform the user that there is an incompatibility in workgroup setting requiring the user to make a decision (and brief instructions on what to do).

As otherwise:

> we are silently undoing the user's previous work on its [read their] `smb` service configuration.

Which seems like the safer option. Especially if folks want to dabble in enabling such as system wide re-configuration when they don't yet appreciate it's scope.

As always it's your call as there may be as yet unseen intracasies in the implementation that require breaking this issue down and spawning further issues. So see how it goes. And thanks for upping the anti on this one. Would be great to get a 'more proper' sort if we can.

**Comment by FroggyFlox** [comment]
Sounds good! I'll go that route and see where I can go with it; hopefully it won't be too much of a rabbit hole.

**Comment by FroggyFlox** [comment]
@phillxnet, I now have a working "proof-of-concept" (unpolished) implementation of such as automatic configuration of the Samba service based on info gathered from the AD server. It seems to work fine after a quick few tests on my end so hopefully it's a good sign.

**Comment by FroggyFlox** [comment]
For instance, when trying to start the Active Directory service with the following configurations...
- AD service domain: samdom.example.com (Workgroup should be `SAMDOM`)
- Samba service workgroup: `MYGROUP`

...we get the following error:
![image](https://user-images.githubusercontent.com/30297881/106368592-d511a380-6318-11eb-8ef3-510751c1c36f.png)
