### ISSUE TITLE
Error mount btrfs rockstor 3.9.2-50

### ISSUE THREAD

**Issue by guino973** [rockstor/rockstor-core#2288]
Hello,
After removing a disk from a rockstor pool and following a reboot, rockstor can no longer mount the filesystem.
[root @ nas-1-ssd mnt2] # btrfs fi show
Label: 'rockstor_rockstor' uuid: bb763b04-0bfd-4c6f-82cf-a86e1760356d
        Total devices 1 FS bytes used 2.89GiB
        devid 1 size 12.40GiB used 6.33GiB path / dev / sdh3

warning, device 8 is missing
bytenr mismatch, want = 20971520, have = 21168128
ERROR: cannot read chunk root
Label: 'primary_storage_cloudstack' uuid: cdcab6fd-189e-4f86-a64a-ced2b2580630
        Total devices 8 FS bytes used 164.67GiB
        devid 1 size 931.51GiB used 202.50GiB path / dev / sdf
        devid 2 size 931.51GiB used 202.50GiB path / dev / sda
        devid 3 size 931.51GiB used 202.50GiB path / dev / sdg
        devid 4 size 232.89GiB used 202.50GiB path / dev / sdd
        devid 5 size 232.89GiB used 202.50GiB path / dev / sde
        devid 6 size 232.89GiB used 202.50GiB path / dev / sdc
        devid 7 size 232.89GiB used 202.50GiB path / dev / sdb
        *** Some devices missing

Label: 'test' uuid: 92aca175-0275-4676-8fc1-32514f5e2137
        Total devices 1 FS bytes used 416.00KiB
        devid 1 size 232.89GiB used 2.02GiB path / dev / sdi

As soon as I run the command:
mount -o degraded / dev / sdf / mnt2 / primary_storage_cloudstack /

The server freezes!

Do you have a solution?
Thank you in advance ...
Regards
Olivier

**Comment by guino973** [comment]
If i want run this command : 
btrfs device delete  detached-6b91fdd0c7e44c01a00e5300a0a7fa7d 
or 
btrfs device delete  6b91fdd0c7e44c01a00e5300a0a7fa7d 
or 
btrfs device delete  5002538e403cf3d3

? 

![rockstor](https://user-images.githubusercontent.com/80522216/110945451-762e4980-831c-11eb-82cd-3cb1a16dd8f8.png)

**Comment by phillxnet** [comment]
@guino973 For support questions such as this I think the forum would be more appropriate.

https://forum.rockstor.com/

> If i want run this command :
> btrfs device delete detached-6b91fdd0c7e44c01a00e5300a0a7fa7d
> or
> btrfs device delete 6b91fdd0c7e44c01a00e5300a0a7fa7d
> or
> btrfs device delete 5002538e403cf3d3

As for deleting missing devices btrfs does accept the word 'missing' as a device identifier. This is what Rockstor uses itself when asked to remove a missing device. But the degraded,rw custom mount options have to be specified, as per the Web-UI instructions, for this to be possible.

Also if the pool is damaged you may only be able to mount degraded,ro.

We do now have a far more up-to-date Release Candidate stage offering of Rockstor 4. And given this is 'Built on openSUSE' rather than our prior run which was CentOS based, you may well have a better time using that, especially in such situations that require pool repair/maintenance as the included btrfs is far newer (by years) and so has many more of the upstream fixes/improvements.

A user story of a similar situation to yours, repairing a pool that had a missing / dead device, came up recently in the following forum thread:

https://forum.rockstor.com/t/help-with-raid10-disk-failure-btrfs-replace-wont-start/7675

Also, all current Rockstor developers are also active forum members.

Hope that helps.

**Comment by FroggyFlox** [comment]
Closing this issue now due to lack of activity and the fact that such support questions are better suited for our forum (as detailed above).
