### ISSUE TITLE
Tests tries to import django_ztask

### ISSUE THREAD

**Issue by chrstphrchvz** [rockstor/rockstor-core#2302]
Trying to run unit tests on a clean build fails when trying to import `django_ztask`. I find that removing `'django_ztask'` from test/test-settings.py avoids this issue. My guess is that as of #2283 `django_ztask` now needs to be removed from `INSTALLED_APPS` in conf/test-settings.conf.in; is that the case?

**Comment by phillxnet** [comment]
@chrstphrchvz Nice find and thanks for the report.

We mostly run the tests without referencing this 'special' config and so this was missed.
And Yes, as of
Replace orphaned django-ztask with Huey (#2276) #2283
we should no longer have any reference to django-ztasks. But we did maintain it's name in some places referencing our internal server names as that made things much simpler in the transition and is simlpy cosmetic so worth the cosmetic cost.

Cheers.

I  was sure I'd removed everything of importance re django_ztask: Oh well, it was rather a large change. But absolutely required in the greater scope of moving to newer Django and Python versions, as referenced in the referenced issue for that pr.

For the time being just run the tests without referencing the test settings if you are keen to proceed. Take a look at a few of the more recent larger pull requests from say @FroggyFlox to see how they have been running the tests since that Huey pr.

Thanks again for the heads up on this one.

**Comment by FroggyFlox** [comment]
@phillxnet, now that these test-settings have been deprecated in #2432 , maybe we should close this issue?

**Comment by phillxnet** [comment]
@FroggyFlox Agreed, and thanks for the tidy-up here.
Closing as:
Fixed by #2434
