### ISSUE TITLE
rockon url is http but rockstor.com is now https

### ISSUE THREAD

**Issue by korg** [rockstor/rockstor-core#2304]
Fix for default url for rockon pull url

#2303 

Hopefully even i cant mess that pull request up. haha.

**Comment by phillxnet** [comment]
@korg Thanks for opening his one, and preparing the requisite pull request.
Linking for context to the recent issue regarding our move of rockstor.com to https:

[Website] Missing HTTPS #2226

That issue didn't quite belong in rockstor-core but at the time we didn't have the more appropriate https://github.com/rockstor/rockstor-website

We have now had https only (with http redirect) since June 17th:
https://forum.rockstor.com/t/rockstor-com-maintenance/7847/5
So a little over a month; with as yet no reported issues.
