### ISSUE TITLE
UI Integer out of Range Error during Scrub

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2397]
Thanks to the analysis and discovery by Rockstor community member Dunkelfalke here:

https://forum.rockstor.com/t/integer-out-of-range/8183/18

it appears that that the information returned by the btrfs-scrub operation generates an overflow in some cases, when the number of discards to be reported exceeds the integer format range of the variable defined in the scrub.py model.

The suggestion is in:
https://github.com/rockstor/rockstor-core/blob/master/src/rockstor/storageadmin/models/scrub.py

replace
https://github.com/rockstor/rockstor-core/blob/81a0d5f5e0a6dfe5a922199828f66eeab0253e65/src/rockstor/storageadmin/models/scrub.py#L43

with
csum_discards = models.BigIntegerField(default=0)

including the corresponding Django migrations to update the database structure.

Would it make sense to also change the other Integer Definitions in this model to _BigInteger_ data types to avoid issues with larger Rockstor installations/large scrub results?

    csum_errors = models.IntegerField(default=0)
    verify_errors = models.IntegerField(default=0)
    no_csum = models.IntegerField(default=0)
    csum_discards = models.IntegerField(default=0)
    super_errors = models.IntegerField(default=0)
    malloc_errors = models.IntegerField(default=0)
    uncorrectable_errors = models.IntegerField(default=0)
    unverified_errors = models.IntegerField(default=0)
    corrected_errors = models.IntegerField(default=0)

**Comment by Hooverdan96** [comment]
When I tested the change (before making an actual pull request), and executed the `migrate`, the additional message popped up:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/35113775/190880401-1488fb1f-661f-4627-a592-7e651018226d.png">

It only allows to proceed when answering `yes`. Is this something to be concerned about?

The migration file resulting from the `makemigrations` has this content:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/35113775/190880424-e7b7cbc1-ae7a-4a9b-91d6-b868c2f4bfa0.png">

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for seeing to this issue's creation and testing your proposed fix. Much appreciated.

> ... the additional message popped up:

Yes we have so-far ignored these just in case. May well try the suggested clean-up in testing in the future before we move to the next stable release but a little guarded about making too many changes just yet.

Given this is a relatively safe change, bar the database migration bit (unavoidable in this case), I was considering this as a master branch candidate.
@FroggyFlox your thoughts on this. It is a critical (i.e. we have observed failure) and trivial (Integer to BigInteger db migration) so fits our newly formalised criteria in developer docs here:

https://rockstor.com/docs/contribute/contribute.html#developers

> Unless your development contribution is both a trivial and critical fix, it likely belongs as a modification against the testing channel only.

Plus I have a number of other smaller fixes I'l like to cherry pick or merge into our first v4 stable update and one is another trivial db change concerned with ordering output only. That would be for scrubs also so that keeps things on-topic also. A complex as I'm also wanting to backport the existing testing improvement work in testing branch to pave the way forward to enable our Python 2 -> 3 efforts.

So in short, if you fancy doing a pr for this that would be much appreciated.

> Would it make sense to also change the other Integer Definitions in this model to _BigInteger_ data types to avoid issues with larger Rockstor installations/large scrub results?

I'm not actually sure, but we could look to the definitions in btrfs for these to know the upstream definition as it were. Best we match those is my thinking: i.e. such as you looked into in your comment here:

https://forum.rockstor.com/t/integer-out-of-range/8183/10

And yes, if we are out of line with them then go for a full-update I say. But not across the board. Lets keep this to scrub only for now. We can address other short-falls similarly in their own migration pull requests if need be, linked to the observed failure in the associated area. Otherwise we end up with larger migrations than need be, with fuzzy links to a variety of things they endu up fixing, that may come back to haunt us.


Thanks for your care here in attribution to Dunkelfalke here. Much appreciated.

**Comment by FroggyFlox** [comment]
> @FroggyFlox your thoughts on this. It is a critical (i.e. we have observed failure) and trivial (Integer to BigInteger db migration) so fits our newly formalised criteria in developer docs here:

Agreed... it is a well-isolated fix too which should make the cherry-picking much easier to handle than if it were a very complex patch.

**Comment by Hooverdan96** [comment]
Ok, I created one ... I interpreted that I should create the Pull Request against the Master Branch? If that was wrong, I assume I can correct that somehow.

I could not really understand how to find out what the underlying data types are in the C programs, so I left good enough alone for now, and only went with the one BigInteger adjustment. If you can give me an example how I can ascertain where these data definitions can be found, let me know, and I'll investigate the other fields as well.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks, yes in this case master works as testing will get via a re-base before our next release in that channel and we can pop directly into Stable updates via a master branch build.
Cheers.

> I could not really understand how to find out what the underlying data types are in the C programs,

They should be in a c header file (*.h) defining the relevant structures, or defined locally, and I had mistakenly thought I saw the same in the referenced forum thread with your earlier examination of this issue:

https://forum.rockstor.com/t/integer-out-of-range/8183/10

And we do have some definitions there.

My apologies. In time we can maybe double check our prior assumption on all these types and what upstream defines them as; and where. It would then be a good idea to add in-code comments to our own models containing references to the upstream definitions to easy later checking to see if any have been redefined in the interim.

**Comment by phillxnet** [comment]
As per my comment here: https://github.com/rockstor/rockstor-core/pull/2374#issuecomment-1287781509
And our current inertia on releases, I'm moving now to first add this to the testing channel where we can then, if need be, later cherry pick for the stable (given it's specificity). Again my apologies for the mixed messaging here. But the extensive changes and unfortunately scope creep of my current testing work of #2400 and our pressure to move to Python 3 there after is rather impacting on the need to re-awaken the testing channel releases as soon as possible and is also potentially pushing us towards having to reassert a new stable from a future snapshot of our current testing. Just to help with collecting the db updates etc. and to help with testing migrations from one stable to another. All still a little in flux unfortunately. And all taking far longer than hoped: hence the suggestion we try to move folks to the newer Django base and test coverage of a newer snapshot of testing (at least until we have to re-do our build system!!). And for that we need testing releases to have in-the-field testing again.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2398
