### ISSUE TITLE
Problems with installing rockstor Built on openSUSE Leap15.4 on raspberry pi 4

### ISSUE THREAD

**Issue by xztd34** [rockstor/rockstor-core#2536]
Hi,

I'm trying to install Built on openSUSE Leap15.4 on a raspberry pi 4 with 2gb via sd card.
The installer starts and installs but at a certain moment it just stops, gives a black screen for 2 seconds and i get the screensaver of my lg tv. Any idea what is going wrong ?
Kind regards, Marc

**Comment by Hooverdan96** [comment]
hi @xztd34. It might make more sense, if you post this issue on our community forum, as that has more visibility and interaction on installation issues. Would you mind to raise this over here, too:

https://forum.rockstor.com/

Any additional info you have on hardware setup, etc. (I assume you can't get any logs at this point, since it just seems to stop?) over there could prove helpful for others to give some advice of what might be going wrong.
Finally, I assume you've been attempting to do this using the 4.5.8-0 image from the download page?

**Comment by phillxnet** [comment]
Linking for context to @xztd34 created issue:
https://forum.rockstor.com/t/problems-with-installing-rockstor-built-on-opensuse-leap15-4-on-raspberry-pi-4/8765

**Comment by Hooverdan96** [comment]
Can this be closed, considering the outcome of the forum discussion? Or are there follow-ups that we need to track here?

**Comment by xztd34** [comment]
Hi, Yes sure the can be closed.

Kr, Marc

**Comment by phillxnet** [comment]
Closing as per @Hooverdan96 follow-up.
