### ISSUE TITLE
(t) nginx error log showing /opt/rockstor/static/js/lib/json2.js failed (2: No such file or directory)

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2550]
Thanks for forum member [jihiggs](https://forum.rockstor.com/u/jihiggs) for surfacing this issue while investigating WebUI access issues:
https://forum.rockstor.com/t/suddenly-unable-to-log-in-to-web-interface/8788

it seems that in the `/opt/rockstor/var/log/nginx/error.log the following error message can be found during login (successful and unsuccessful logins) on an unmodified installation of Rockstor 4.5.9-1 (line breaks are mine for readability):

```
[error] 1701#1701: *2 open() “/opt/rockstor/static/js/lib/json2.js” failed (2: No such file or directory), 
client: 192.168.1.100, server: ~^(?.+)$, 
request: “GET /static/js/lib/json2.js HTTP/1.1”, 
host: “192.168.1.107”, 
referrer: “https://192.168.1.107/login_submit”
```

This message might have been around before, but was not discovered until now.

**Comment by Hooverdan96** [comment]
I looked for some instances which might be causing this problem. The error message above already asserts that the `json2.js` library is missing (not sure when it was removed). It seems that the reference still exists here:

https://github.com/rockstor/rockstor-core/blob/bdc3df2762ceddf355b482ca50f698654e342861/src/rockstor/storageadmin/templates/storageadmin/login.html#LL66C1-L69C63

The reference also used to be in the `setup.html` and `base.html` at some point, but was removed from those files, however remained in the `login.html`.

May be it's as easy as removing the reference from that `html` file, since it's referencing a non-existing library anyway...

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks, that jogged my memory on the recent clean-up I did (incompletely by the looks of it); see:
pr #2452 
issue #2451
We can simply drop this reference. Not sure how I missed it thought !
The linked issue in the above pull request (in rockstor-jslibs) is this one:

pr https://github.com/rockstor/rockstor-jslibs/pull/26
issue https://github.com/rockstor/rockstor-jslibs/issues/18

As such this issue is an artefact of "remove redundant json2.js - rockstor-jslibs related #2451 #2452"
and me having missed a reference.

I say we address this and remove the rouge (missed) reference before it comes back to haunt us again.
