### ISSUE TITLE
Remove dependency on 'future'

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2698]
Ironically our dependency on the 'future' python import is approaching the time when its utility is reversed. This library has aided us in our transition from older Python versions to newer. However as we approach Python 3.11 (3.12 specifically) we also must address the future removal :). See the following comment from a buildbot contributor: https://github.com/buildbot/buildbot/issues/6980#issue-1817029978

Quoted here, in small part, for convenience:

> ... future will no longer work with Python 3.12 because imp module has been removed from stdlib and the situation will be even worse with 3.13 because the lib2to3 which is the core of the future will be removed from stdlib as well.

**Comment by eli-schwartz** [comment]
From a very quick look through your codebase it appears you do not use `import future` at all, nor depend on it in pyproject.toml? 

Note that:
-  the python 2/3 compatibility library `future` (https://python-future.org/ or https://pypi.org/project/future/)

is not the same as
- the standard library advance previews module `__future__` (https://docs.python.org/3/library/__future__.html)

In particular, the latter does not strictly have anything to do with python 2 (although 4 of its 9 feature previews were introduced in python 2 and became the default in python 3) plus it cannot really break on later versions of python due to being in the stdlib.

**Comment by phillxnet** [comment]
@eli-schwartz Thanks, this was quite the surprise. I was certain we had this hanging around somewhere! But sure enough as yoru say:
```
grep -R "import future\|from future"
```
produces nothing. I'll close as a result. 

Again thanks for your effort there. I had created this issue, from memory, when I read that comment, to tag it as a TODO/check-up. But apparently entirely in error. Nice.

Closing as fixed re advice from @eli-schwartz
