### ISSUE TITLE
Change "Disabled" to "Quotas Disabled" in Web-UI

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2810]
We have the following header & example content in shares overview:

| `Pool (Active mount options / Status) Quotas` |
| -- |
| pool-name (rw,relatime,space_cache,subvolid=5,subvol=/) Enabled |

Which is meant to indicate the 3 infomational items: Pool (name), mount options/status, Quota status.

However when the RED Disabled appears in the 'Quotas' position:

| `Pool (Active mount options / Status) Quotas` |
| -- |
| pool-name (rw,relatime,space_cache,subvolid=5,subvol=/) Disabled |

 it can too easily lead to an inaccurate/misleading inference that the Share itself is disabled.

It is proposed that we instead specify that it is the Quotas that are disabled by the explicit use of **Quotas Disabled** in this warning message text.

**Comment by Hooverdan96** [comment]
If this should only be done on the Shares Screen, then the change would have to be done here:

https://github.com/rockstor/rockstor-core/blob/4d690efcb1a5ff99addbd06e417b82b103393e43/src/rockstor/storageadmin/static/storageadmin/js/templates/share/shares_table.jst#L24-L59

changing the text from `Disabled` to `Quotas Disabled` in Line 46

I tested the change, and that seems to do it:

![image](https://github.com/rockstor/rockstor-core/assets/35113775/ff5f7d26-3b6f-439a-886d-e4791865a695)

For consistency, once could also change the wording from `Enabled` to `Quotas Enabled` in Line 44.

If you wanted to influence this also in the Pool page, it will be slightly more involved. 

Probably here:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/static/storageadmin/js/views/pools.js#L135-L160

change the `text` in line 139 and 158 (even though that seems to be non-functional at the moment).

And here in Line 299:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/static/storageadmin/js/views/pools.js#L294-L300


![image](https://github.com/rockstor/rockstor-core/assets/35113775/8ed17dbe-d418-47b1-8056-f8cefc43f1b5)

Do affect the drop-down, the text values also have to be changed over here:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/storageadmin/static/storageadmin/js/views/pool_details_layout_view.js#L201

But on the pool page it might not matter all that much, since there is a dedicated column for quotas, so that should be self-explanatory.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for looking into this one. Much appreciated.

> changing the text from `Disabled` to `Quotas Disabled` in Line 46

That was my thinking also. I just created the issue quickly as was focused elsewhere and wasn't sure if we did it like this or used a model value. So yes this would do it nicely I think.

> For consistency, once could also change the wording from `Enabled` to `Quotas Enabled` in Line 44.

Agreeed.

> If you wanted to influence this also in the Pool page, it will be slightly more involved.

I think it is less critical there: as quotas has it's very own column: so is far less subject to miss-interpretation.

> But on the pool page it might not matter all that much, since there is a dedicated column for quotas, so that should be self-explanatory.

Exactly.

Since you've basically fix this issue (Shares side), do you fancy presenting a PR. It's a safe/simple change after-all. And we could then get this into the next testing release: and consequently our pending Stable.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2818
