### ISSUE TITLE
Feature: snapshot visibility for smb share

### ISSUE THREAD

**Issue by debejerry** [rockstor/rockstor-core#475]
When connecting a smb share through MS windows it would be good to have shadow copy like access to the created snapshots

**Comment by schakrava** [comment]
Since we added support for custom samba configuration in #555 , shadow copy access can be added by adding custom configuration(described by @jjlauer above) to a samba export from the web-ui.

If users really want it, we can add specific support of this at a later time. 

Please feel free to add your comments.

**Comment by cron410** [comment]
This will be a welcome addition to Rockstor. Please implement it. I'll put a $10 bounty on it!

**Comment by schakrava** [comment]
This is now supported from the Web-UI and can be setup very easily. Support was just added as part of #715 and merged into 3.8-8 update.

Here's the documentation: http://rockstor.com/docs/windows-shadow-copy.html
