### ISSUE TITLE
Console access from the Web-UI

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#518]

**Comment by MFlyer** [comment]
Hi all @priyaganti @phillxnet @schakrava , here is a preview for ongoing shell access implementation on Rockstor, hope you'll enjoy it :smiley: 

https://youtu.be/ekGDnPxj13E

Todo list

- [ ] Increase nginx security to avoid direct access to shell page outside Rockstor (testing)
- [ ] Add shellinabox service management over services page
- [ ] Add shellinabox service customization (define different port and maybe black on white shell css)

**Comment by phillxnet** [comment]
@MFlyer This looks great, you are really knocking out some great stuff. Good luck with the security side, not something I can help with unfortunately (the security side). I take if from the text within the video that initial login is to be limited to admin user only, with su to root there after, is that right? Does this mean that the admin password is over https (as normal) and the root password is then inside a ssh session of it's own which is in turn also inside the https?

**Comment by MFlyer** [comment]
Hi @phillxnet , security side is a challenge to me too eheheh (had to find a way to let shell only inside Rockstor without locking it at all - not so easy because of shellinabox structure and probably only possible with some nginx hacks)

>  I take if from the text within the video that initial login is to be limited to admin user only, with su to root there after, is that right? Does this mean that the admin password is over https (as normal) and the root password is then inside a ssh session of it's own which is in turn also inside the https?

First part you're right!
Shellinabox configured to only allow access from localhost with LOGIN auth that is like a tty login (root user hasn't login auth so we ensure 2 logins: any web-ui created user next su with root) where you should never auth directly with root (our choice :) )
Less secure alternative: SSH auth allowing direct root login (not our choice!)

**HTTPS**

Actually there's a new nginx location named shell (48a953f) that acts like on socket.io address, shellinabox not directly on https because of proxy_pass with current django-nginx already on https (django-nginx over https -> access to /shell address -> nginx proxy_pass moves to http://127.0.0.1:4200, not exposed to frontend, like socket.io), so yes, we're always under https :+1: 

Flyer

**Comment by MFlyer** [comment]
Nginx security / avoid direct access to shell : 02c5a92 :wink: 

Obviously someone hacking could modify http request header, but:

1. This assumes he/she already knows about Rockstor on lan
2. He/she knows Rockstor hostname/ip 

And if 1 & 2...he/she has to know a Rockstor web ui account infos (uname&pass) and Rockstor root pass

I think current protection can be ok

Flyer

**Comment by MFlyer** [comment]
Hi all, on 5080e8f, 4b7abda, 24cd465 and a0cc630 got a nicely switchable Shellinaboxd service :smiley: 

**_Customization_**
- port customization not required because under nginx proxy (so no direct access)
- css customization? Maybe! :)
- access method (LOGIN or SSH) customization?? What do you think about that @schakrava @phillxnet (I'd prefer force only LOGIN more secure auth - that let only uid>1000 users to log + next su command)

Flyer

**Comment by MFlyer** [comment]
Hi fellows,
we've got a working configuration page for shellinabox.
Color scheme : switch between classic white on black and black on white
Connection service: as already explained LOGIN means no direct login for uid<1000 (no root login) and su is required, SSH is like a common ssh connection (direct root login ok)
![shell](https://cloud.githubusercontent.com/assets/17988902/16706976/93096d30-45c0-11e6-858f-36f92bfdc405.jpg)
