### ISSUE TITLE
Import existing BTRFS pool

### ISSUE THREAD

**Issue by akawoz** [rockstor/rockstor-core#534]
Since BTRFS kernel support improves frequently I'm currently running my 16TB pool on Ubuntu 14.10. Using partitions not full disk. Please include support to import an existing configured pool. Keep up the great work.

**Comment by schakrava** [comment]
@akawoz As of 3.5-0, Rockstor is being shipped with a later kernel. 3.5-0 comes with 3.17.1 kernel and the next update will further bump it up to 3.18.1. Hope this helps you.

I am thinking about adding support such that Shares can be created inside the root pool. This doesn't allow importing arbitrary pools, but does let you use the root disk for data. This is different from what you originally asked for, but thought you might be interested.

**Comment by akawoz** [comment]
@schakrava thanks for the update - I've gone through the process of removing drives from the pool one-by-one and converting them to BTRFS full disks and re-adding to the pool. So I'm at least compliant on that angle :-)

As soon as you guys support importing an existing pool I'll be installing Rockstor ASAP.

Keep up the great work!

**Comment by freeurmind** [comment]
So as btrfs doesn't have explicit import/export, I assume the following does the job after a head migration
  # btrfs device scan --all-devices
  # mkdir /mnt/mypool
  # mount /dev/sdx /mnt/mypool

Anyone has the experience or did this before welcome to comment :-)

**Comment by schakrava** [comment]
This issue is closed by #680 

The work on this issue resulted in comprehensively improving the behavior around Pools, Shares and Snapshots in the following way. Pools, Shares and Snapshots created outside of it's API or some how not in the Rockstor state are automatically detected and synchronized. Warnings and error messages provide manual commands in case of unsupported cases like nested subvolumes and snapshots. Repeat installations also get a nifty feature with this merge. If Rockstor is installed over an existing  or broken install due to a root disk failure etc.. all preexisting data in the form of pools, shares and snapshots are automatically imported. Another advantage is that drives can be moved to another Rockstor machine where data can be imported from the UI with a few clicks, facilitating a reasonable recovery option.
