### ISSUE TITLE
Feature: Linux 3.19 Release Supports Parity Scrubbing

### ISSUE THREAD

**Issue by baggar11** [rockstor/rockstor-core#592]
When available, update OS to Kernel 3.19 to allow support for scrubbing of parity devices. IE: Raid5/6. Thanks!

**Comment by schakrava** [comment]
@baggar11 Thanks for filing this issue. We've been somewhat secretly looking forward to this moment. I've already begun testing the kernel.

**Comment by hakuryuu675** [comment]
Any update on the status of this? We're well past 3.19 at this point as far as kernel releases go.

**Comment by schakrava** [comment]
@hakuryuu675 we've had issues with 3.19 kernels while testing. Things are looking better with 4.0 but need further testing. So the update is that soon we hope to update the kernel, and it's looking more like 4.x. I can't say for sure how long we have, but a reasonable estimation is either 3.7-7 or 3.7-8 release.

**Comment by hakuryuu675** [comment]
4.x sounds great to me! Thanks for the update.

**Comment by baggar11** [comment]
Any news on testing parity scrubbing on 3.7-9 since it's using kernel 4.0.2?

**Comment by schakrava** [comment]
Things have been pretty good on 4.0.2 since it was made default in Rockstor couple of releases ago. I've been testing 4.1 and it's planned to become default soon. In both versions scrubbing on raid5/6 is working fine. On the btrfs mailing list I see a discussion about missing devices in relation to scrubbing, but I think that's a separate issue.

I don't think there is any additional coding work necessary for this issue.
