### ISSUE TITLE
Cannot create visible snapshot with a Space in the snapshot name

### ISSUE THREAD

**Issue by cron410** [rockstor/rockstor-core#622]
This is my 3rd snapshot. I was attempting to create snapshots while testing where i can write in a share  over SAMBA. Error below:

    Error!
    
    Unknown client error doing a POST to /api/shares/storage/snapshots/strucutre root

**Comment by cron410** [comment]
Looks like it doesnt matter that I had folders everywhere. It seems to be a bug. I am running 3.6-9 on a fresh install today. This is my first time using Rockstor.

**Comment by cron410** [comment]
Here are my current snapshots in case you need more info:
    structure3	March 16th 2015, 9:50:34 pm	Visible	Yes	0 bytes	0 bytes	 
    structure2	March 16th 2015, 9:50:00 pm	Visible	Yes	16.00 Kb	16.00 Kb	 
    structure	March 16th 2015, 9:45:38 pm	Visible	Yes	16.00 Kb	16.00 Kb	 
    snap2	March 16th 2015, 9:12:57 pm	Hidden	No	16.00 Kb	16.00 Kb	
    snap1	March 16th 2015, 9:11:51 pm	Visible	Yes	16.00 Kb	16.00 Kb

**Comment by schakrava** [comment]
@cron410 Thanks for your helpful comments.

**Comment by cron410** [comment]
I'm just really excited for this project to mature.

**Comment by schakrava** [comment]
@cron410 Thanks! Care to leave a review on sourceforge and/or our forums for others?

**Comment by schakrava** [comment]
@cron410 This bug is triggered because you are trying to create a snapshot with a space in it's name.

I really don't want to support spaces in names. @Mchakravartula id making changes to raise an error telling the user that spaces are not allowed in snapshot names.

I think this is the right thing to do -- not allow spaces in snapshot/share/pool names. It just prevents a lot of potential issues we can face by allowing spaces. I like to keep the design simple. If you feel otherwise, please make your case.

**Comment by cron410** [comment]
@schakrava @Mchakravartula Sounds logical. I would also like to know other's input on this issue. Another option could be to silently replace the spaces with underscores and if someone doesn't like the underscores, they can either not use spaces, or add some sort of punctuation of their choosing.

**Comment by schakrava** [comment]
Fixed by #625
