### ISSUE TITLE
data-collector re-enabled by visiting system page

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#660]
To reproduce (works almost every time):-
- login to WebUI and see the Dashboard page
- turn OFF Metric Collection via the switch with that label (note if it's off already the bug still exists)
- visit the System page (do nothing there but the next step)
- reboot by using the admin button (top right) while still on the System page.

Almost every time Metric Collection / data-collector will be re-enabled when the machine reboots even though it was manually disabled on the Dashboard page (via the Metric Collection switch) and showed as disabled when we visited the System page in the above scenario.

I know it's not important but it may well be covering up / the cause of some other issues.

N.B. this is on slow but above or equal to min spec real hardware.

**Comment by phillxnet** [comment]
Rockstor version 3.7-9 by the way.
It seems that if I turn off the data-collector service at the System page but other than that follow the same procedure as above the data-collector is still re-enabled upon reboot (mostly).

N.B. if I do not visit the system page after having turned off (at the Dashboard) the Metric Collection and rebooting from the admin button but this time from the Dashboard the data-collector remains off over the initiated reboot more often, but not always.

**Comment by phillxnet** [comment]
@gkadillak I'm hoping your recent marathon Bootstrap upgrade patch set in issue #672  helps here, ie flaky events from UI components.

**Comment by gkadillak** [comment]
Yes, I was planning on bundling this issue into that pull request.

**Comment by phillxnet** [comment]
@gkadillak That's great thanks.

**Comment by phillxnet** [comment]
@gkadillak I have done some more investigation into this and narrowed it down a tad:-

disable data-collector close all web UI access and reboot machine via VM not webUI
I then login via ssh.
I have put trust (rather than md5)  on local postgres access in /var/lib/pgsql/data/pg_hba.conf
That way I can see what the DB knows of stuff.
'''
psql -U postgres
\connect smartdb

select smart_manager_servicestatus.status, smart_manager_servicestatus.service_id, smart_manager_service.name from smart_manager_service join smart_manager_servicestatus on smart_manager_service.id = smart_manager_servicestatus.service_id where status = 't';
 status | service_id | name 
--------+------------+------
(0 rows)
'''
all services are disabled to keep things simpler
and this look good as the data-collector is also not showing up as is to be expected.

If I then open a browser (Firefox in this case) and its home page is set to either Dashboard or System then the above DB query will then show:-
'''
 status | service_id |      name      
--------+------------+----------------
 t      |          9 | data-collector
(1 row)
'''
This takes a varying time to inadvertently alter the DB to this data-collector enabled state.
System page visit up to 5 seconds to change DB
Dashboard page visit up to 24 seconds to change DB
In both cases the DB is changed to have the data-collector enabled (t) when it wan't until these pages were viewed (no action is taken on these pages).

I am not sure if this is related to your recent pull request, hence me requesting instructions on how to try out your patches; I see now that @schakrava has just left me some pointer there so I'll give it a go.

If this issue, given the above additional info, now doesn't seem related; do you have any pointers as to where to look next in the code so that I might help.  Quite a few black boxes left for me I'm afraid.

Thanks and I will attempt now to follow Suman's advise in your pull request.

**Comment by schakrava** [comment]
@phillxnet and @gkadillak Thanks for debugging this issue and providing useful information. I looked into it this morning and found the root cause. data collector daemon is one of rockstor service(unlike say, samba or nfs which are directly managed by systemd) and is managed by supervisord. The configuration file that rockstor service(via supervisord) looks at when you reboot(or simply restart with systemctl restart rockstor) is located at /opt/rockstor/etc/supervisord.conf. The relevant section for data collector is 

; Data Collector
[program:data-collector]
environment=DJANGO_SETTINGS_MODULE=settings
command=/opt/rockstor/bin/data-collector ; the program (relative uses PATH, can take
; args)
process_name=%(program_name)s ; process_name expr (default %(program_name)s)
numprocs=1                    ; number of processes copies to start (def 1)
priority=200
autostart=true                ; start at supervisord start (default: true)
autorestart=unexpected        ; whether/when to restart (default: unexpected)
startsecs=2                   ; number of secs prog must stay running (def. 1)
startretries=3                ; max # of serial start failures (default 3)
exitcodes=0,2                 ; 'expected' exit codes for process (default 0,2)
stopsignal=TERM               ; signal used to kill process (default TERM)
stopwaitsecs=5               ; max num secs to wait b4 SIGKILL (default 10)
stdout_logfile=/opt/rockstor/var/log/supervisord_%(program_name)s_stdout.log
; stdout log path, NONE for none; default AUTO
stdout_logfile_maxbytes=1MB   ; max # logfile bytes b4 rotation (default 50MB)
stdout_logfile_backups=10     ; # of stdout logfile backups (default 10)
stderr_logfile=/opt/rockstor/var/log/supervisord_%(program_name)s_stderr.log
; stderr log path, NONE for none; default AUTO
stderr_logfile_maxbytes=1MB   ; max # logfile bytes b4 rotation (default 50MB)
stderr_logfile_backups=10     ; # of stderr logfile backups (default 10)

When the data collector is turned off, the current code just stops the supervisor service. In addition, we need to set autostart=false to make the change persistent.

So this is unrelated to anything frontend and certainly not to the bootstrap upgrade. let's work on this separately.

**Comment by phillxnet** [comment]
@schakrava Great find; so the initial WebUI visit after reboot to either Dashboard or System is just causing the database to be re-synced with what is found to be running then?  This seems back to front though.  But then I haven't looked at Django yet either.  This fix will be a winner for those trying to keep disk writes down though.

**Comment by schakrava** [comment]
Some what related optimization to push along with this issue: change the pic locations to /run instead of /opt/rockstor/var/run. /run is tmpfs and avoids problems caused by stale pid files.

**Comment by therealprof** [comment]
Sorry to hijack this but I'm having the same problem but also the other way round: Data Collector will always come up but the real vital services will not: I've Samba, NFS, AFP and Task Scheduler on but after a reboot only Data Collector and AFP will be started.
