### ISSUE TITLE
vmware esxi 5.1 - disk uuid issue or webui issue?

### ISSUE THREAD

**Issue by oliver68** [rockstor/rockstor-core#666]
hi folks, heard of rockstor in a magazine i read in regularly and cause of brtfs i decide to test in vmware esxi. installation ok, but examining the webui, specially the disks part a red message with 'Warning! Disk serial number or UUID is not legitimate or unique.' got my attention.

research leads me to closed issue 'empty disk serial number #545'. from this input i added 'disk.EnableUUID="true"' to my vmx file. restarted rockstor still shows up mentioned red box and warning for disks? via ssh to esxi prooving with 'vmkfstools -J getuuid' shows up an uuid for each vmdk!

so, need help to live with the red boxes for disks. whats the problem here? 
thx in advance
oliver

**Comment by phillxnet** [comment]
Does the message that you got consist of the following text?

"Warning! Disk serial number or UUID is not legitimate or unique.
Disk names may change unfavorably upon reboot, errors and replacement resulting in data loss. This error is caused by the source of these disks such as your Hypervisor or SAN. Please ensure that disks are provided with unique serial numbers before proceeding futher "

I get this when trying to use VirtIO Drives from within Virtual Machine Manager and KVM.  My work around was to change the Disk bus to SATA, not ideal but that did it for me.  I don't know if such a configuration is possible in esxi land, just to get you going for now.

Note that I also found that adding a serial number (my only obvious option in virt-manager) did not help, virt-manager defaulted to an empty serial number.

Also if the cause is the same it may assist developers in reproducing the problem and testing fixes given the greater ease of setting up virt-manager and kvm than an esxi system.  An as yet unpublished howto on installing Rockstor on kvm via vmm is in the rockstor-doc github repo.  Just needs a data drive to be VirtoIO instead of SATA (as in the howto) to reproduce the above error.  Install drive still needs SATA as otherwise the installer fails see issue #602 .

**Comment by oliver68** [comment]
thx for your quick response and yes your noted message occurs for each virtual hdd on esxi51 scsi-controller not relevant which is configured. i have not seen any issues during installation.

to test more esxi51 specific i setup rockstor on a virtual disk with IDE-controller without issues during install and this boot disk shows up correct without warning, but there are only 4 channels per vm in esxi. for booting it is ok, i think!

all afterwards added disks on any type of SCSI controller are shown up <b>with</b> the UUID warning mentioned. other controllers are not available.

![image](https://cloud.githubusercontent.com/assets/3930504/8007483/3fdc66f8-0b9c-11e5-859a-cb1e2682760d.png)

so in this constellation with esxi51, there is actually no solution visible to me. 

any ideas wthout debugging code desirable? oliver

**Comment by schakrava** [comment]
@oliver68 Pools can be unstable if Disks don't have unique ids. when you need to replace drives or if they appear with different names after a reboot/reconnect, it can be a mess. 

There probably is a config option in vmware to fix that. Here's the command that will save you time to verify without having to fire up the ui: /usr/bin/lsblk -P -o NAME,MODEL,SERIAL,SIZE,TRAN,VENDOR,HCTL,TYPE,FSTYPE,LABEL,UUID

Here's the forum discussion that may be of help: http://rockstor.com/forums/index.php?p=/discussion/comment/22/#Comment_22

**Comment by phillxnet** [comment]
I think I see the problem (at least for vda block devices):-

/usr/bin/lsblk -P -o NAME,MODEL,SERIAL,SIZE,TRAN,VENDOR,HCTL,TYPE,FSTYPE,LABEL,UUID

on a vda (a virtio drive in KVM) gives the following:-

NAME="vda" MODEL="" SERIAL="" SIZE="2G" TRAN="" VENDOR="0x1af4" HCTL="" TYPE="disk" FSTYPE="" LABEL="" UUID=""

so no serial from lsblk but my /etc/libvirt/qemu/rockstor3.7.xml has my fake serial entered via Virtual Machine Manager:-
<disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/original-test-volume.qcow2'/>
      <target dev='vda' bus='virtio'/>
      <serial>11111111111111111111</serial>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </disk>
Imagination is a great thing, at least I expect it is.

But:-
udevadm info --query=all --name=/dev/vda | grep ID_SERIAL
gives:-
E: ID_SERIAL=11111111111111111111
My shiny serial.

@oliver68 could you also try (as well as Suman's suggested command) the following udevadmin command on your sdb once you've done what you can to give it a serial, it might be that your disk.EnableUUID="true" also awards it a serial.  My vda still has no UUID, just need to see what udevadm can see on your Esxi system as what we are really after is the serial number which identifies the drive rather than a partition (UUID)

udevadm info /sys/class/block/sdb

or whatever you problem device is called

Please post the output of Suman's command and the above udevadm command (adjusted to reference a problem device)

**Comment by oliver68** [comment]
Ok, first of all thx for your great support and awsome reaction time. :+1: 

I decided to test from ground up with resetting vm to point after installation.

First i added a scsi disk and ended up with same result for sdb with red box shown.
Command <b>'lsblk -P ...'</b> shows that there is no uuid set on disk.

Second i edited the vmware vmx file and added option <b>disk.EnableUUID="TRUE"</b>.
After restarting rockstor vm same issue again. Same output on <b>'lsblk -P ...'</b>.

As a last chance i removed entry of rockstor vm from vsphere client and readded it immediatly to ensure reloading the vmx file. and what the hell - everything works as expected. a little bug in vsphere client. good to know for others i hope ... :-)

![image](https://cloud.githubusercontent.com/assets/3930504/8043045/9aa64f5c-0e23-11e5-9db1-bd5e3b0fadec.png)

again thx for support, a soluttion for esxi is found from my point of view.
testing other features can go on to get an alternative open source nas named rockstor for the future ...

**Comment by phillxnet** [comment]
@oliver68 Well done; and thanks for sharing your find / fix.

**Comment by phillxnet** [comment]
@schakrava I could open a new issue for the vda KVM virtio block devices as looks like it's unrelated now.

**Comment by phillxnet** [comment]
@schakrava Looks like this issue is now close worthy.
@oliver68 I am assuming you are now happy.

**Comment by oliver68** [comment]
oh yes, solved and happy. :+1:

**Comment by schakrava** [comment]
@phillxnet :+1:
