### ISSUE TITLE
pool no longer mounted

### ISSUE THREAD

**Issue by jamesj2** [rockstor/rockstor-core#674]
I've been out of town for a few days.  After back I tried to access my SMB share to find it was empty.  After some research it looks like my raid1 pool is no longer mounted.   I couldn't find an active mount entry and the /mnt2/pool1 directory is empty.  The web interface still shows pool1 as being setup and shows me how much space is used/left and my drives are online.  I tried running `btrfs device scan --all-devices` but it doesn't output anything.   I ended up trying to update rockstor to 3.8-0 using the 4.0.2 elrepo kernel but no luck.  Any suggestions?

**Comment by schakrava** [comment]
btrfs device scan not showing any output is normal. You can run "btrfs fi show" to see all pools. I'd be interested in that output.

If HDs are all showing online on the web-ui, then the problem may not be missing drives. It could be due to errors on some HD. What does smart info look like in the ui? You can click on a HD can look at smart info and even run some tests.

dmesg may also provide some clues. if you rather not share any information publicly, feel free to email support@rockstor.com

**Comment by jamesj2** [comment]
Schakrava,

That's good to know that btrfs device scan normally doesn't show anything.  Below is the output of  "btrfs fi show".  I wasn't able to run the smartctl tests through the web ui.  I'm getting a "Unsupported command(test/sdb). Valid commands are wipe, btrfs-wipe, btrfs-disk-import, blink-drive, enable-smart, disable-smart" error.  So I ran the short tests by hand and all looks good so far.  The long tests are currently running.   I'll email you the server and dmesg logs.

```
Label: 'rockstor_rockstor'  uuid: 9f9f90ea-6fdf-433c-b88c-d123f3db991b
        Total devices 1 FS bytes used 17.11GiB
        devid    1 size 457.38GiB used 20.04GiB path /dev/sda3

Label: 'pool1'  uuid: 07eb4f46-5d04-4bd8-9cf6-b0bcd402a15d
        Total devices 4 FS bytes used 1.58TiB
        devid    1 size 931.51GiB used 895.02GiB path /dev/sdb
        devid    2 size 931.51GiB used 896.00GiB path /dev/sdc
        devid    3 size 931.51GiB used 895.01GiB path /dev/sdd
        devid    4 size 931.51GiB used 896.01GiB path /dev/sde

btrfs-progs v4.0
```

Thanks for the quick reply!

**Comment by utting** [comment]
I think I have just come up against this same issue.  All the Samba shared drives have disappeared off the network, even after rebooting.  Now with the Web UI, I find that the shares are all still showing on the GUI and say they contain 50Gb and 200Gb of data (correct size), but Samba clients see them as empty.

And when I log into the Rockstor machine manually, /mnt2/videos/ is indeed empty (same for all the other shares).  But all the data is still there in /mnt/rockstor_rockstor/videos etc!
(These shares are on the main system disk.)
Restarting Samba, or rebooting does not fix this.  The shares stay empty.

btrfs fi show output looks okay.
dmesg doesn't show any obvious errors (but I'm not too familiar with its normal output).
This problem has happened after upgrading to Rockstor 3.7-5 (a couple of months ago).

Is there any way of rebuilding/reconnecting the shares to the data?
Thanks, Mark

**Comment by jamesj2** [comment]
Uttig,

Hmm.. My /mnt2/rockstor_rockstor is empty.  I don't know if this is by design since it's my boot drive. 

I've been working with rockstor support via email and what I've found is my pool wasn't getting mounted.   Here are most of the steps I've done so far.  

Ran `btrfs fi show` and my pool is shown.
```
# btrfs fi show
Label: 'rockstor_rockstor'  uuid: 9f9f90ea-6fdf-433c-b88c-d123f3db991b
        Total devices 1 FS bytes used 17.26GiB
        devid    1 size 457.38GiB used 20.04GiB path /dev/sda3

Label: 'pool1'  uuid: 07eb4f46-5d04-4bd8-9cf6-b0bcd402a15d
        Total devices 4 FS bytes used 1.58TiB
        devid    1 size 931.51GiB used 814.02GiB path /dev/sdb
        devid    2 size 931.51GiB used 814.00GiB path /dev/sdc
        devid    3 size 931.51GiB used 814.01GiB path /dev/sdd
        devid    4 size 931.51GiB used 814.01GiB path /dev/sde
```

Tried mounting the pool by label `mount /dev/disk/by-label/pool1 /mnt2/pool1` it failed.  So then I tried mounting each device /dev/sd{b,c,d,e} separately (I have 4 drives as raid1) to /mnt2/pool1.  Some of them gave me the following error but others were successful in mounting the pool.  Note: you only have to successfully mount one of the drives in the pool to be able to access your data.
```
mount: wrong fs type, bad option, bad superblock on /dev/sdd,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

dmesg output:

[48838.891848] BTRFS: device label pool1 devid 3 transid 8347 /dev/sdd
[48838.893074] BTRFS info (device sdd): disk space caching is enabled
[48838.893078] BTRFS: has skinny extents
[48838.893741] BTRFS: failed to read the system array on sdd
[48838.907059] BTRFS: open_ctree failed
```

Since then I've rebooted and ran `btrfs device scan` and was able to mount the pool by label `mount /dev/disk/by-label/pool1 /mnt2/pool1`.  And I'm currently running `btrfs balance start /mnt2/pool1` to see if my issue clears up completely.

After being able to mount the pool by hand my shares haven't started working.  I think there is another mount that is needed for that.

**Comment by schakrava** [comment]
@jamesj2 thanks for sharing the synopsis of our debugging.

@utting before you try anything else, can you try the following?
1. systemctl stop rockstor
2. btrfs device scan
3. systemctl start rockstor
4. check the mounts manually with mount, ls, cd, etc.. commands to see if your data is back in /mnt2/videos and other shares?

If these steps get your shares back, then the issue is with btrfs scan not being run or something like that. It still doesn't make sense to me because the issue did not get triggered after a reboot, did it?

Please report back after the above steps and we'll go from there. I don't see this on our machines here, but it would be helpful if we can reproduce this behavior.

**Comment by utting** [comment]
Suman,

Thanks for your suggestions.
I did the first three steps that you suggested.
The 'btrfs device scan’ showed no output.
Neither did the systemctl commands.

Then the /mnt2/videos etc shares were still empty.

I think I’ll back everything up onto an external disk and then start from scratch.

Thanks
Mark

Dr Mark Utting
Senior Lecturer, ICT
School of Business | Faculty of Arts and Business
University of the Sunshine Coast
Tel: +61 7 5459 4495
Email: utting@usc.edu.au<mailto:utting@usc.edu.au>



On 13 Jun 2015, at 12:46 am, Suman Chakravartula <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesj2<https://github.com/jamesj2> thanks for sharing the synopsis of our debugging.

@utting<https://github.com/utting> before you try anything else, can you try the following?
1. systemctl stop rockstor
2. btrfs device scan
3. systemctl start rockstor
4. check the mounts manually with mount, ls, cd, etc.. commands to see if your data is back in /mnt2/videos and other shares?

If these steps get your shares back, then the issue is with btrfs scan not being run or something like that. It still doesn't make sense to me because the issue did not get triggered after a reboot, did it?

Please report back after the above steps and we'll go from there. I don't see this on our machines here, but it would be helpful if we can reproduce this behavior.

—
Reply to this email directly or view it on GitHub<https://github.com/rockstor/rockstor-core/issues/674#issuecomment-111516298>.

University of the Sunshine Coast, Locked Bag 4, Maroochydore DC, Queensland, 4558 Australia.
CRICOS Provider No: 01595D
Please consider the environment before printing this email.
This email is confidential. If received in error, please delete it from your system.

**Comment by schakrava** [comment]
Closed as this is not directly related to any code task. Feel free to start a forum topic if you need to start this question again.
