### ISSUE TITLE
AFP broken

### ISSUE THREAD

**Issue by javahaxxor** [rockstor/rockstor-core#707]
Cannot share a folder (share) created in a pool other than the main disk. Old AFP shares have stopped working. iotop shows "afpd -d -F /etc/netatalk//afp.conf" please notice the double slashes.
version 3.8-1

**Comment by javahaxxor** [comment]
Mysteriously this solved itself overnight

**Comment by schakrava** [comment]
@javahaxxor double slashes is a cosmetic issue, but not a real problem. The root cause of this problem has to do with netatalk software version. In the newer version the config location changed and updating to the latest Rockstor does magically fix the problem. I suspect that's what happened here, though somewhat mysteriously. The mystery has to do with a intermediate version when things were broken. Glad this is no longer a problem.
