### ISSUE TITLE
UI extremely sluggish

### ISSUE THREAD

**Issue by javahaxxor** [rockstor/rockstor-core#708]
It takes around 10 seconds to render the response for any click. Several restarts have not helped . 3.8-1

**Comment by schakrava** [comment]
Can you provide more information? Chrome developer tools can show you what's going on. network and console tabs are where i'd first look.

storage(disks/pools/shares/snapshots) screens did get slower in the last update because we are checking for state changes due to possible external changes(admin manually tinkering with btrfs). All this is bound to get better after #706 work is merged.

**Comment by javahaxxor** [comment]
![rockstor1](https://cloud.githubusercontent.com/assets/3932029/8433689/a0fa074c-1f47-11e5-9be6-19b2bbd639ff.png)
![rockstor2](https://cloud.githubusercontent.com/assets/3932029/8433688/a0ecf0fc-1f47-11e5-8c48-e324d3192240.png)
![rockstor3](https://cloud.githubusercontent.com/assets/3932029/8433687/a0ecce38-1f47-11e5-86e6-8a741338e105.png)

The sluggishness dissapeared overnight also but during the investigation I saw some exceptions, one in some performance code, one when editing AFP shares

**Comment by gkadillak** [comment]
Is the UI back to functioning to normal?

**Comment by javahaxxor** [comment]
Yes. The strange thing is that a reboot didn't have any effect

**Comment by javahaxxor** [comment]
Yes. The strange thing is that a reboot didn't have any effect

**Comment by schakrava** [comment]
Perhaps the issue was purely client (browser) side or network related.
