### ISSUE TITLE
Optimize Rockstor for flash deployments

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#725]
Two scenarios to support here.

1. Rockstor installed on an ssd (eg: NUC)
2. Rockstor installed on a usb flash drive

In both cases, filesystems on the root disk should be mounted with noatime and certain kernel parameters tuned. Further more, in case (1), fstrim should be setup to run periodically.

Following links provide more information
https://wiki.archlinux.org/index.php/Solid_State_Drives
http://blog.neutrino.es/2013/howto-properly-activate-trim-for-your-ssd-on-linux-fstrim-lvm-and-dmcrypt/
http://www.certdepot.net/rhel7-extend-life-ssd/
https://gist.github.com/ngnpope/3806732
http://www.cyrius.com/debian/nslu2/linux-on-flash/
http://www.storagesearch.com/ssd.html
http://superuser.com/questions/228657/which-linux-filesystem-works-best-with-ssd#answer-550308
http://lists.freedesktop.org/archives/systemd-devel/2015-March/029842.html

**Comment by phillxnet** [comment]
Some concerns with fstrim (1)  that I think we just circumvented by moving to kernel 4.1 are that quite a few SSD's are advertising to the system that they can do NCQ trim when in fact they can't; and hard lock or corruption ensues; Samsung 8* and their recent firmware updates to fix other serious problems but added this ncq trim issue have brought this to popular attention. I was looking into this re the Rockstor kernel recently by way of a thread for the forum about our kernel.

My understanding is that our elrepo ml kernel inherited these particular samsung HORKAGE patches with this commit:-
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/drivers/ata/libata-core.c?id=9a9324d3969678d44b330e1230ad2c8ae67acf81&h=linux-4.1.y

That same file has a list of various devices that have been "accounted for" via this ATA_HORKAGE_NO_NCQ_TRIM and other special work arounds.

Don't like the fstrim on every boot as that ensures we will always have slow boots and also 24/7 machines will miss out. Discard mount option seems generally disapproved off and rather over kill.  Ubuntu do a cron / anacron once a week ie /etc/cron.weekly/fstrim

# trim all mounted file systems which support it
/sbin/fstrim --all || true

I looked into disk schedulers and for ssd at least deadline was fine and is what Rockstor currently uses and Ubuntu default to this also:-
cat /sys/block/sda/queue/scheduler
However I was looking from desktop point-of-view.

The which file system link is a bit old but where we have ext it has to be ver4 for trim which it is (our /boot).

Does CentOS 7 not already have a service to do this, the arch link above mentions a systemd timer service which seems like the way to go.

On usb flash (much lower quality) maybe we should default to Metric Collection off or have a special note on this.

**Comment by schakrava** [comment]
I did a bunch of research and testing yesterday in this matter, should've just asked you. One of the changes I made is setup a systemd timer to run fstrim weekly. However, the fstrim with centos7 is a bit old so it doesn't have -a option. We'll just update it when that happens. The nice thing about disk scheduler is that it's automatically set to deadline by the os if the drive is not sata.

I agree with the metric collection suggestion. It's coming by the way of #660

**Comment by therealprof** [comment]
Okay, after testing the new version I can say that the changes brought pretty much nothing on top of my own changes which reduced the amount of writes to a quarter:

> $ iostat
> Linux 4.1.0-1.el7.elrepo.x86_64 (rockstor) 	17.07.2015 	_x86_64_	(2 CPU)
> 
> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>           14,60    0,00    3,46    1,45    0,00   80,49
> 
> Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
> ...
sdc               1,06        12,99        35,55     466404    1276618
> ...

The writes with 3.8-2 and 3.8-3 are at an unchanged average of 35kB/s which is still to much for an SD card to sustain for a long time...

**Comment by schakrava** [comment]
@therealprof Thanks for putting it to test. I'd like to understand your setup better. But first, you should know that the optimizations are applied on system startup if the root disk is detected to be either a flash drive or ssd. So, you might want to reboot if you haven't after going from 3.8-2 to 3.8-3.

I'd very much like to get to the bottom of this and see if we can add any more optimizations. So please provide more details about your setup. If you choose not to give out any info publicly, you can always email me(suman@rockstor.com). You are running Rockstor off USB flash drive, correct? Can you explain what you mean by your own changes?

**Comment by therealprof** [comment]
@schakrava I did a reboot, however every reboot with this system is somewhat nerve wrecking because it usually doesn't come back up until I reboot into recovery mode using the grub menu and back into the normal system.

Okay, so some background: The system is a HP MicroServer Gen8 and I'm running it from an SD card which is actually visible under Linux as a Virtual rotational disc not an SSD.

I applied many changes because the setup would write many hundred KBs per second if I hadn't.

Some of the highlights are:
- I moved the postgres pg_xlogs into a tmpfs mount and tuned the parameters to prevent excessive write outs, the first of which has the unconvenient drawback that I have to reset the xlog after every reboot before the database comes back up. I helps quite a lot with the writes but I still think that running postgresql is a huge mistake and overkill.
- I symlinked /var/netatalk to the share which keeps the data itself, otherwise a time machine backup would thrash the SD card in no time. However this again has a drawback because netatalk seems to start before rockstor here especially when rockstor cannot start due to the postgres problem so the mount is not available.
- / is remounted with "mount -o remount,noatime,commit=120,nospace_cache /" which is a *huge* improvement
- /tmp is mounted as /tmpfs
- SMART and datacollection are turned off

After all these changes writes are on an acceptable level in the few kB per minute level (after writing around 300MB while I manually adjust some things) but it's very inconvenient.

**Comment by schakrava** [comment]
Great feedback @therealprof We can definitely improve based on your suggestions. One quick question, I am wondering what the IO scheduler for your ssd is. Can you share the output of the following command? (In the command I made the assumption that your ssd is sda)

```cat /sys/block/sda/queue/scheduler```

**Comment by therealprof** [comment]
[root@rockstor rockstor]# cat /sys/block/sda/queue/scheduler
noop [deadline] cfq 
[root@rockstor rockstor]# cat /sys/block/sdb/queue/scheduler
noop [deadline] cfq 
[root@rockstor rockstor]# cat /sys/block/sdc/queue/scheduler
noop [deadline] cfq 
[root@rockstor rockstor]# cat /sys/block/sdd/queue/scheduler
noop [deadline] cfq 

sda and sdb are SSDs, sdc is the SD card I'm booting from and sdd is a HDD.

**Comment by schakrava** [comment]
thanks @therealprof this is useful. Is sdd not sata? I am curious why deadline scheduler is the default for HDD.

**Comment by therealprof** [comment]
SDD is an external USB drive which is a funny story by itself: I bought a Toshiba Canvio Basics drive cheaply with the intention to disassemble it and put it in my NAS. However this drive does not have the usual USB<->SATA bridge but is really a native USB drive...
