### ISSUE TITLE
syncthing rockstor not connecting

### ISSUE THREAD

**Issue by xavierle** [rockstor/rockstor-core#826]
i run several syncthing nodes
on debian, ubuntu and openmediavault plugin

the synchting node on the rockstor appliance is unable to connect to any other node

**Comment by schakrava** [comment]
Ok, I've given this a thorough test here at home and all my devices(phones and other linux laptops) are syncing well with the Syncthing Rock-on. Device discovery seems to take a few seconds as expected but sometime a bit longer and unpredictable. But they always connect.

It may be that in your case there is a firewall issue. Either way, this report is best posted on the forum(forum.rockstor.com) and not here on github. If there is a Rockstor bug, it needs to be defined more thoroughly with reproducible steps. I know it's hard in this case, and that's why I think that forum is a better place where other members can help troubleshoot and narrow it down.

**Comment by fago** [comment]
I ran into the same problem - it is not able to build up a direct connection. I figured that the UDP discovery port mapping is wrong in the docker image and created a PR there, see https://github.com/istepanov/docker-syncthing/pull/3. Not sure whether something has to be adapted on the syncthing side of things also?

**Comment by phillxnet** [comment]
@fago That's a nice find, thanks. And explains why an existing install (using the older default port) worked OK.
I have opened an issue over in our rockon-registry repository that you are more than welcome to co-ordinate the port change on. I have prepared an issue containing your supplied details against which a pull request can be logged.
http://rockstor.com/docs/contribute.html#making-changes
please see issue:
https://github.com/rockstor/rockon-registry/issues/40
Would be good to have you as a 'code contributor' in that repo and make attribution easier.
Cheers.
