### ISSUE TITLE
Improve "Contribute to Rockstor" documentation

### ISSUE THREAD

**Issue by vinima** [rockstor/rockstor-core#893]
The current documentation lists steps for contributing to Rockstor core.  However, the corresponding steps for contributing to Rockstor doc are missing.

**Comment by phillxnet** [comment]
@vinima I had a look at the required additional packages to build the rockstor-doc repo today.
The would be required as steps to build the docs to test them prior to pull requests.
It no longer builds using python3 due to a dict index change between python2 and python3.
So python2 variants of the sphinx packages and on an ubuntu 15:04 install I needed:-

sudo apt-get install python-sphinx python-sphinxcontrib.youtube

and

pip install --user sphinxcontrib-fulltoc

had to use pip here as the sphinxcontrib-fulltoc package wasn't available in default Ubuntu 15:04  repos as a package.

Noting here as current for today's build of docs.

**Comment by schakrava** [comment]
Closing this as it should be in rockstor-doc repo instead.
