### ISSUE TITLE
If I change the IP address, the mgmt interface, and some other stores of information do not update

### ISSUE THREAD

**Issue by roweryan** [rockstor/rockstor-core#917]
It's showing the old IP under /home#appliances and in the header bar.

**Comment by roweryan** [comment]
Also /etc/issue.rockstor gets appended each time the network config is changed, instead of being overwritten.

**Comment by roweryan** [comment]
And /etc/hosts still shows the old original entry.

**Comment by roweryan** [comment]
Aha! this old /etc/hosts entry is causing some problems

**Comment by roweryan** [comment]
Updating /etc/hosts and rebooting doesn't (no longer?) fixes the problem with the mgmt interface/appliance page. Both still show the old ip.

**Comment by schakrava** [comment]
@roweryan the /etc/hosts part will be fixed separately as part of #896. 

The remaining issues from all of your comments are fixed by the pull request referenced. You'll be able to test after the next testing update. Just follow the forum as I know you will. Thanks for reporting this issue and helping me fix it fast!
