### ISSUE TITLE
removed a defective disk, storage disk showing wrong disk details

### ISSUE THREAD

**Issue by frederick-lemasson** [rockstor/rockstor-core#937]

**Comment by frederick-lemasson** [comment]
Just removed a failing disk and after a reboot Rockstor shows the previous (sane) disk details on the storage/disk page, hopefully clicking on the trash will delete the removed disk, but I can't dare clicking the trash button with the details from a perfectly working disk drive showed here on the same line ...

![capture du 2015-10-09 21 48 23](https://cloud.githubusercontent.com/assets/7714032/10403933/942a5f12-6ecf-11e5-9cf4-711a0f6f0d2a.png)

**Comment by phillxnet** [comment]
@frederick-lemasson Thanks for reporting and the pic helps to see your point. I think this is due in part to many modern systems re-arranging their drives each time they boot up. It used to be that if a drive was sda it was sda for ever unless is was repositioned electrically but these days after a reboot it could well be sdb, or sdc etc. However Rockstor identifies drives by their serial number but for historical and probably human readable reasons displays the name as sda, sdb, etc. 

But given that, yes it should be showing the previous disk's serial etc. How did you remove the failing disk? ie did you use command line tools etc? Does anything change after you press the Rescan button? Before the failing disk was removed, was it listed as sda (but with it's own serial etc)? Thanks for helping with this as it is disconcerting.

I believe I have just reproduced your findings but going through it again to check, I will post here once I've confirmed.

**Comment by phillxnet** [comment]
OK, reproduced in 3.8-8.05 testing.
before:-
![before-drive-removed](https://cloud.githubusercontent.com/assets/2521585/10410697/971e0e72-6f41-11e5-8881-23fe943b2ed9.png)
Then I shut this vm down and removed from it's spec the vdb drive with serial of fake-serial-00002 (effectively unplugging it) booted up vm again and we have:-
![after-drive-removed](https://cloud.githubusercontent.com/assets/2521585/10410712/e3b2c94e-6f41-11e5-8922-5ac41c7e7d3e.png)
And so we have what looks like the same.
ie vdc has become vdb and taken it's serial with it of course.
But rather than the serial of the missing drive we have the serial of the previous occupier of vdc which is now vdb; likely an artefact of how this display is generated.
@frederick-lemasson does that look to you like a reproduction of your experience.

Looks like a bug / possible enhancement to me as showing the details of an existing drive not the removed drive which is at least disconcerting.

**Comment by phillxnet** [comment]
@frederick-lemasson Incidentally once I had clicked on the bin icon of the misreading fake-serial-00003 (which we are assuming is actually fake-serial-00002 drive but missing) I was left with the following:-
![after-drive-deleted](https://cloud.githubusercontent.com/assets/2521585/10410813/e520b856-6f44-11e5-802a-7a98a4b20534.png)
If you are at all worried just make sure you have all your data backed up first, I think this is a cosmetic reporting issue / bug; but definitely a disconcerting one.

**Comment by frederick-lemasson** [comment]
Hi Philip, 

That is effectively a reproduction of what I experience.
I physically removed the failing disk, without doing anything on the rockstor interface or linux system, should I have ?
Also clicking on rescan doesn't change anything.

**Comment by frederick-lemasson** [comment]
The page Storage/Pools/Raid1 also displays this incorrect data.
Also nowhere Rockstor tells me that a disk from My Raid1 is missing or that my data is no more fully replicated (I have a 4T and a 1T disks left)
Any sort of "danger red blinking thingy" would be nice I think.

**Comment by phillxnet** [comment]
I am now looking into this issue as I think it's root cause is shared with a number of other (referenced) issues that have a higher impact on usability / functionality.

**Comment by phillxnet** [comment]
N.B. removing the last drive in the list appears to work as expected ie in the following the sdd serial QM00011 was removed and displays the correct and now missing serial number that is used to uniquely identify it:-
![3rd-data-removed-and-labeled-successfully](https://cloud.githubusercontent.com/assets/2521585/11607600/71492450-9b44-11e5-995e-804545c6bc8a.png)

**Comment by phillxnet** [comment]
Same goes for removing the second drive in a two drive system, ie sdc QM00009 was correctly labeled as missing with it's original also missing serial number:-
![2nd-of-2-drives-removed-ok](https://cloud.githubusercontent.com/assets/2521585/11607656/cd10a31a-9b46-11e5-854d-765a8b84afd9.png)

**Comment by phillxnet** [comment]
Smallest fail test case so far is 2 data drives with the 1st removed ie has lower serial number and earlier dev name.

Before removal:-
![1st-of-2-removed-before](https://cloud.githubusercontent.com/assets/2521585/11607706/f9625bcc-9b49-11e5-8215-65b3e1aef472.png)

After removal of earlier sdb QM00007 2GB drive:-
![1st-of-2-removed-after](https://cloud.githubusercontent.com/assets/2521585/11607713/6b4ce306-9b4a-11e5-9e06-118b80903620.png)

Note that in this case the removed drive has the serial and size of the drive that previously occupied it's current (fake) location prior to the removal rather than its actual serial and size and maybe it's previous location (dev name), in this case QM0007 2GB. This is consistent with my original fail test case with 3 drives.

N.B. system/btrfs/scan_disks returns Disk collection correctly ie only those disks currently attached along with their correct serial numbers.

**Comment by phillxnet** [comment]
I am in the process of extending update_disk_state so that it successfully and accurately maintains information about removed devices. I have moved to naming removed disks by a random uuid as the name is used as the db index. This will hopefully also make more obvious any attempt to use removed or missing devices. Device name is also transient so storing missing / removed / offline drives under real device names seemed untenable, potentially misleading.

Image showing 2 removed disks with their correct Serial numbers and sizes:-
![2-removed-disks](https://cloud.githubusercontent.com/assets/2521585/11615649/219edc9a-9c5e-11e5-8f8d-bf34b55b9f04.png)

Image showing one of the removed disks (serial = QM00013) having been replaced:-
![qm00013-reattached](https://cloud.githubusercontent.com/assets/2521585/11615653/629bfffc-9c5e-11e5-8985-eaf79e46e695.png)

@schakrava Do you see any glaring issues with this approach? Also I have an outstanding issue of not being able to delete these uuid entries via the bin icon, nothing in rockstor.log and:-

Error!
Unknown client error doing a DELETE to /api/disks/16fd28bf-8c56-4732-a22f-9ed7ae07f063

I am looking to src/rockstor/storageadmin/static/storageadmin/js/views/disks.js next and should be able to continue with this tomorrow.
Do you have any pointers as to why the DELETE is not working. Thanks.

**Comment by phillxnet** [comment]
@schakrava No worries on DELETE question, I found the issue; django api call rejected due to no match ie uuid's starting with a letter delete fine. Looking into the fix now.

**Comment by phillxnet** [comment]
Forgot to mention I had also removed the dash "-" chars which were also throwing the match.

**Comment by phillxnet** [comment]
Pull request ready for review.

**Comment by phillxnet** [comment]
Pull request more ready for review than last time, especially since we are now at the beginning of a new testing channel cycle.
