### ISSUE TITLE
custom web-ui port

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#983]
Currently web-ui port(443) cannot be changed from the web-ui. Some users seem to want it.

http://forum.rockstor.com/t/appliances-management-port/601

**Comment by neyfrota** [comment]
add my 5 cents here:

Change nginx is the easy part... Big problem is: some rockstor systems need api at 443.... Try this:

- ssh
- change nginx config https port to 1443 (or any other)
- reboot your rockstor
- ssh again
- RESULT: You notice NO pools/shares are mounted.. just basic root
- change nginx config https port back to 443
- reboot your rockstor
- ssh again
- RESULT: all your pools shares are mounted
 
So my guess is: rockstor startup service need api to perform some tasks

Im now looking how to change "current appliance" settings ... my guess if i explain my appliance lives at 1443, rockstor startup scripts will obey and we have peace in system again

Does any one has experience on that?

**Comment by holmesb** [comment]
The mgmt_port variable appears to be set to 443 by [appliance.py](https://github.com/rockstor/rockstor-core/blob/9dbdb6b1ed945f894c425b9ab84b785d9c041b01/src/rockstor/storageadmin/models/appliance.py). But there are [58 references to 443 in the code](https://github.com/rockstor/rockstor-core/search?utf8=%E2%9C%93&q=443), and [some of these are hard-coded](https://github.com/rockstor/rockstor-core/blob/06fefb6934b3a2f96588998daa68097f5cef6517/src/rockstor/storageadmin/views/network.py) rather than use the mgmt_port variable. So the solution is probably to allow mgmt_port to be changed in appliance.py then replace the hard-coded references elsewhere with mgmt_port.

**Comment by phillxnet** [comment]
Linking to another forum threat with a use case involving for this feature involving openvpn:
https://forum.rockstor.com/t/openvpn-over-tcp/1457

**Comment by greghensley** [comment]
It looks like this was partially taken care of by cc3c89a2c4e6b82f541f3b45c2852fa9760823aa, which included a setting for the HTTPS listener port in the rockstor service settings.  However, I still see two areas for improvement:

1. It needs another option to disable the default redirection of port 80 -> https
2. Updating the setting regenerates rockstor's `nginx.conf`, but the change is not persistent across updates of the rockstor package.
 - That is, the config database maintains the custom port setting but `nginx.conf` is replaced by the default copy from the package.  Since `nginx.conf` is only updated _when the setting is changed_, rather than when the rockstor service is started, you have to access the web interface on port 443 again, go to the rockstor service settings, and hit `Submit` to recreate `nginx.conf` with the correct port.

**Comment by schakrava** [comment]
@greghensley Thanks for listing the problems. You saved me time, appreciate it!
