### ISSUE TITLE
Dashboard crashes if left open for a long time

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#998]
Behavior reported on both firefox and chrome browsers.

Not sure if it only happens on dashboard or other screens. It could be that we are not purging some data of dashboard widgets and as it grows over time, browser kills the tab -- just a guess at this point.

http://forum.rockstor.com/t/dashboard-crashes-chrome-tab/640

**Comment by MFlyer** [comment]
Hi @schakrava, i was with a Rockstor Dashboard window open for a long time and I realized that because of cpu fan screaming, so i decided to have some tests:

Removing line charts or having just 1 out of 3 seems to solve and after some documenting and more testing i suppose it's because of d3 behaves on svg.

Reading around I found we should use instead an html5 canvas solution ( [canvas.js](http://canvasjs.com/docs/charts/chart-types/html5-line-chart/) is a good/easy one ), that better perform over chrome/safari/firefox (read some benchmarks having better frame per second with canvas, in the order of 2:1)

Flyer

**Comment by MFlyer** [comment]
Hi all,
working on Dashboard widgets probably I discovered why we have a "client cpu eater":

- CPU widget runs over jQuery Flot for barchart (canvas) and d3.js (svg) for linechart (tons of updates drawing chart line & consuming cpu)
- Net stats widgets with a line chart with multiple lines (always d3.js svg) and this probably is our bottleneck (more than cpu widget)

Actually coding to chart.js over cpu widget (both barchart and linechart), next step is for net widget and others

To @schakrava : can I remove jQuery Flot or used elsewhere in rockstor??

Flyer

**Comment by MFlyer** [comment]
Hi all @schakrava @phillxnet and @priyaganti ,
happy to announce that with 66be6c9 had a nice working dashboard left open 2 hours (CPU, Net and Memory Widgets) without any browser crash or freeze :sparkles: 

Working on Memory widget to complete it, than moving to last 4 widgets

Flyer/Mirko

**Comment by MFlyer** [comment]
Some news
Finished Top Shares widget update on #1439 and all is fine.
Going on with Pool Capacity and Usage Widget (Top Shares clone)

Flyer
